
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const BestiaryStatus = {
  public: 'public',
  private: 'private',
  unlisted: 'unlisted'
} as const

export type BestiaryStatus = (typeof BestiaryStatus)[keyof typeof BestiaryStatus]


export const SupporterStatus = {
  none: 'none',
  wirmling: 'wirmling',
  greatwyrm: 'greatwyrm'
} as const

export type SupporterStatus = (typeof SupporterStatus)[keyof typeof SupporterStatus]


export const StatblockLayout = {
  SL_2014: 'SL_2014',
  SL_2024: 'SL_2024'
} as const

export type StatblockLayout = (typeof StatblockLayout)[keyof typeof StatblockLayout]


export const StatblockDesign = {
  BestiaryBuilder: 'BestiaryBuilder',
  Beyond: 'Beyond',
  Odyssey: 'Odyssey',
  MonsterManual: 'MonsterManual'
} as const

export type StatblockDesign = (typeof StatblockDesign)[keyof typeof StatblockDesign]


export const SRDVersion = {
  SRD_2014: 'SRD_2014',
  SRD_2024: 'SRD_2024'
} as const

export type SRDVersion = (typeof SRDVersion)[keyof typeof SRDVersion]


export const Editor = {
  Code: 'Code',
  Visual: 'Visual'
} as const

export type Editor = (typeof Editor)[keyof typeof Editor]
