import "./bestiaries";
import "./creatures";
import "./critterdb";
import "./discord";
import "./login";
import "./search";
import "./staticData";
import "./user";
import "./validation";
import "./automations"