/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
export declare const SearchOptions: t.TIface;
export declare const Stat: t.TUnion;
export declare const Statblock: t.TIface;
export declare const Misc: t.TIface;
export declare const FeatureHeaderTexts: t.TIface;
export declare const Description: t.TIface;
export declare const Core: t.TIface;
export declare const Speed: t.TIface;
export declare const Unit: t.TUnion;
export declare const SpeedEntity: t.TIface;
export declare const SenseEntity: t.TIface;
export declare const Abilities: t.TIface;
export declare const Stats: t.TIface;
export declare const Saves: t.TIface;
export declare const SaveEntity: t.TIface;
export declare const SkillsEntity: t.TIface;
export declare const Defenses: t.TIface;
export declare const Hp: t.TIface;
export declare const Ac: t.TIface;
export declare const Features: t.TIface;
export declare const FeatureEntity: t.TIface;
export declare const SpellCasting: t.TIface;
export declare const InnateSpells: t.TIface;
export declare const CasterSpells: t.TIface;
export declare const InnateSpellsList: t.TIface;
export declare const InnateSpellsEntity: t.TIface;
export declare const SpellSlotEntity: t.TIface;
declare const exportedTypeSuite: t.ITypeSuite;
export default exportedTypeSuite;
//# sourceMappingURL=types-ti.d.ts.map