import { library } from "@fortawesome/fontawesome-svg-core";

import {
	faArrowRightFromBracket,
	faArrowRightToBracket,
	faBars,
	faCircleInfo,
	faCode,
	faCopy,
	faEarthEurope,
	faEye,
	faEyeSlash,
	faGripVertical,
	faHourglass,
	faLink,
	faLock,
	faMagnifyingGlass,
	faPenToSquare,
	faPlus,
	faSave,
	faScaleBalanced,
	faShareNodes,
	faSkull,
	faSpinner,
	faStar,
	faTag,
	faThumbTack,
	faTrash,
	faUserLock,
	faWandSparkles,
	faXmark
} from "@fortawesome/free-solid-svg-icons";
import { faDiscord, faGithub, faPatreon } from "@fortawesome/free-brands-svg-icons";
import { faClipboard, faImage } from "@fortawesome/free-regular-svg-icons";

library.add(
	faArrowRightFromBracket,
	faArrowRightToBracket,
	faBars,
	faClipboard,
	faCircleInfo,
	faEarthEurope,
	faEye,
	faEyeSlash,
	faGripVertical,
	faHourglass,
	faLink,
	faLock,
	faMagnifyingGlass,
	faPenToSquare,
	faPlus,
	faScaleBalanced,
	faShareNodes,
	faSkull,
	faStar,
	faTag,
	faThumbTack,
	faTrash,
	faUserLock,
	faXmark,
	faDiscord,
	faGithub,
	faPatreon,
	faImage,
	faSave,
	faWandSparkles,
	faCopy,
	faCode,
	faSpinner
);
