import { library } from "@fortawesome/fontawesome-svg-core";

import {
    faTrash,
    faLock,
    faSkull,
    faBars,
    faPenToSquare, 
	faStar, 
	faHourglass,
    faUserLock,
    faScaleBalanced,
    faShareNodes,
    faArrowRightFromBracket,
    faArrowRightToBracket,
    faLink,
    faEarthEurope,
    faXmark,
    faPlus,
    faThumbTack, 
	faMagnifyingGlass,
    faTag, 
	faGripVertical,
    faEyeSlash,
    faEye,
    faCircleInfo
} from "@fortawesome/free-solid-svg-icons";
import { faDiscord, faPatreon, faGithub } from "@fortawesome/free-brands-svg-icons";
library.add(
	faTrash,
	faXmark,
	faStar,
	faLock,
	faLink,
	faSkull,
	faEarthEurope,
	faPenToSquare,
	faDiscord,
	faHourglass,
	faUserLock,
	faScaleBalanced,
	faShareNodes,
	faArrowRightFromBracket,
	faArrowRightToBracket,
	faPatreon,
	faGithub,
	faBars,
	faPlus,
	faThumbTack,
	faMagnifyingGlass,
	faTag,
	faGripVertical,
	faEyeSlash,
	faEye,
	faCircleInfo
);
