
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.9.1
 * Query Engine version: e922089b7d7502aff4249d5da3420f6fa55fc6ad
 */
export const prismaVersion: PrismaVersion = {
  client: "7.9.1",
  engine: "e922089b7d7502aff4249d5da3420f6fa55fc6ad"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * Resolved type of the argument passed to the `PrismaClient` constructor.
 *
 * When called without a narrower options type (the common case), this resolves
 * to `PrismaClientOptions` directly, which produces a clear TypeScript error
 * message (`not assignable to parameter of type 'PrismaClientOptions'`) when
 * the argument is missing or incomplete. When the user supplies a narrower
 * options type (e.g. via a literal), it falls back to `Subset` to keep
 * filtering out unknown properties.
 */
export type PrismaClientConstructorArgs<Options extends PrismaClientOptions> =
  [PrismaClientOptions] extends [Options] ? PrismaClientOptions : Subset<Options, PrismaClientOptions>;

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    ((Without<T, U> & U) | (Without<U, T> & T)) & object
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Bestiary: 'Bestiary',
  Creature: 'Creature',
  Automation: 'Automation',
  AutomationCollection: 'AutomationCollection',
  AutomationCollectionEditor: 'AutomationCollectionEditor',
  BestiaryEditor: 'BestiaryEditor',
  UserBestiaryBookmark: 'UserBestiaryBookmark',
  UserBestiaryOrder: 'UserBestiaryOrder'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "bestiary" | "creature" | "automation" | "automationCollection" | "automationCollectionEditor" | "bestiaryEditor" | "userBestiaryBookmark" | "userBestiaryOrder"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Bestiary: {
      payload: Prisma.$BestiaryPayload<ExtArgs>
      fields: Prisma.BestiaryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BestiaryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BestiaryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        findFirst: {
          args: Prisma.BestiaryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BestiaryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        findMany: {
          args: Prisma.BestiaryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>[]
        }
        create: {
          args: Prisma.BestiaryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        createMany: {
          args: Prisma.BestiaryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BestiaryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>[]
        }
        delete: {
          args: Prisma.BestiaryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        update: {
          args: Prisma.BestiaryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        deleteMany: {
          args: Prisma.BestiaryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BestiaryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BestiaryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>[]
        }
        upsert: {
          args: Prisma.BestiaryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryPayload>
        }
        aggregate: {
          args: Prisma.BestiaryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBestiary>
        }
        groupBy: {
          args: Prisma.BestiaryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BestiaryGroupByOutputType>[]
        }
        count: {
          args: Prisma.BestiaryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BestiaryCountAggregateOutputType> | number
        }
      }
    }
    Creature: {
      payload: Prisma.$CreaturePayload<ExtArgs>
      fields: Prisma.CreatureFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CreatureFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CreatureFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        findFirst: {
          args: Prisma.CreatureFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CreatureFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        findMany: {
          args: Prisma.CreatureFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>[]
        }
        create: {
          args: Prisma.CreatureCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        createMany: {
          args: Prisma.CreatureCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CreatureCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>[]
        }
        delete: {
          args: Prisma.CreatureDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        update: {
          args: Prisma.CreatureUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        deleteMany: {
          args: Prisma.CreatureDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CreatureUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CreatureUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>[]
        }
        upsert: {
          args: Prisma.CreatureUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CreaturePayload>
        }
        aggregate: {
          args: Prisma.CreatureAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCreature>
        }
        groupBy: {
          args: Prisma.CreatureGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CreatureGroupByOutputType>[]
        }
        count: {
          args: Prisma.CreatureCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CreatureCountAggregateOutputType> | number
        }
      }
    }
    Automation: {
      payload: Prisma.$AutomationPayload<ExtArgs>
      fields: Prisma.AutomationFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AutomationFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AutomationFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        findFirst: {
          args: Prisma.AutomationFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AutomationFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        findMany: {
          args: Prisma.AutomationFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>[]
        }
        create: {
          args: Prisma.AutomationCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        createMany: {
          args: Prisma.AutomationCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AutomationCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>[]
        }
        delete: {
          args: Prisma.AutomationDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        update: {
          args: Prisma.AutomationUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        deleteMany: {
          args: Prisma.AutomationDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AutomationUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AutomationUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>[]
        }
        upsert: {
          args: Prisma.AutomationUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationPayload>
        }
        aggregate: {
          args: Prisma.AutomationAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAutomation>
        }
        groupBy: {
          args: Prisma.AutomationGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationGroupByOutputType>[]
        }
        count: {
          args: Prisma.AutomationCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationCountAggregateOutputType> | number
        }
      }
    }
    AutomationCollection: {
      payload: Prisma.$AutomationCollectionPayload<ExtArgs>
      fields: Prisma.AutomationCollectionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AutomationCollectionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AutomationCollectionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        findFirst: {
          args: Prisma.AutomationCollectionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AutomationCollectionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        findMany: {
          args: Prisma.AutomationCollectionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>[]
        }
        create: {
          args: Prisma.AutomationCollectionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        createMany: {
          args: Prisma.AutomationCollectionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AutomationCollectionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>[]
        }
        delete: {
          args: Prisma.AutomationCollectionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        update: {
          args: Prisma.AutomationCollectionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        deleteMany: {
          args: Prisma.AutomationCollectionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AutomationCollectionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AutomationCollectionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>[]
        }
        upsert: {
          args: Prisma.AutomationCollectionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionPayload>
        }
        aggregate: {
          args: Prisma.AutomationCollectionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAutomationCollection>
        }
        groupBy: {
          args: Prisma.AutomationCollectionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationCollectionGroupByOutputType>[]
        }
        count: {
          args: Prisma.AutomationCollectionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationCollectionCountAggregateOutputType> | number
        }
      }
    }
    AutomationCollectionEditor: {
      payload: Prisma.$AutomationCollectionEditorPayload<ExtArgs>
      fields: Prisma.AutomationCollectionEditorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AutomationCollectionEditorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AutomationCollectionEditorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        findFirst: {
          args: Prisma.AutomationCollectionEditorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AutomationCollectionEditorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        findMany: {
          args: Prisma.AutomationCollectionEditorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>[]
        }
        create: {
          args: Prisma.AutomationCollectionEditorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        createMany: {
          args: Prisma.AutomationCollectionEditorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AutomationCollectionEditorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>[]
        }
        delete: {
          args: Prisma.AutomationCollectionEditorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        update: {
          args: Prisma.AutomationCollectionEditorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        deleteMany: {
          args: Prisma.AutomationCollectionEditorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AutomationCollectionEditorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AutomationCollectionEditorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>[]
        }
        upsert: {
          args: Prisma.AutomationCollectionEditorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AutomationCollectionEditorPayload>
        }
        aggregate: {
          args: Prisma.AutomationCollectionEditorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAutomationCollectionEditor>
        }
        groupBy: {
          args: Prisma.AutomationCollectionEditorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationCollectionEditorGroupByOutputType>[]
        }
        count: {
          args: Prisma.AutomationCollectionEditorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AutomationCollectionEditorCountAggregateOutputType> | number
        }
      }
    }
    BestiaryEditor: {
      payload: Prisma.$BestiaryEditorPayload<ExtArgs>
      fields: Prisma.BestiaryEditorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BestiaryEditorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BestiaryEditorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        findFirst: {
          args: Prisma.BestiaryEditorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BestiaryEditorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        findMany: {
          args: Prisma.BestiaryEditorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>[]
        }
        create: {
          args: Prisma.BestiaryEditorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        createMany: {
          args: Prisma.BestiaryEditorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BestiaryEditorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>[]
        }
        delete: {
          args: Prisma.BestiaryEditorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        update: {
          args: Prisma.BestiaryEditorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        deleteMany: {
          args: Prisma.BestiaryEditorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BestiaryEditorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BestiaryEditorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>[]
        }
        upsert: {
          args: Prisma.BestiaryEditorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BestiaryEditorPayload>
        }
        aggregate: {
          args: Prisma.BestiaryEditorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBestiaryEditor>
        }
        groupBy: {
          args: Prisma.BestiaryEditorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BestiaryEditorGroupByOutputType>[]
        }
        count: {
          args: Prisma.BestiaryEditorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BestiaryEditorCountAggregateOutputType> | number
        }
      }
    }
    UserBestiaryBookmark: {
      payload: Prisma.$UserBestiaryBookmarkPayload<ExtArgs>
      fields: Prisma.UserBestiaryBookmarkFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserBestiaryBookmarkFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserBestiaryBookmarkFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        findFirst: {
          args: Prisma.UserBestiaryBookmarkFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserBestiaryBookmarkFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        findMany: {
          args: Prisma.UserBestiaryBookmarkFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>[]
        }
        create: {
          args: Prisma.UserBestiaryBookmarkCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        createMany: {
          args: Prisma.UserBestiaryBookmarkCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserBestiaryBookmarkCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>[]
        }
        delete: {
          args: Prisma.UserBestiaryBookmarkDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        update: {
          args: Prisma.UserBestiaryBookmarkUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        deleteMany: {
          args: Prisma.UserBestiaryBookmarkDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserBestiaryBookmarkUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserBestiaryBookmarkUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>[]
        }
        upsert: {
          args: Prisma.UserBestiaryBookmarkUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryBookmarkPayload>
        }
        aggregate: {
          args: Prisma.UserBestiaryBookmarkAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserBestiaryBookmark>
        }
        groupBy: {
          args: Prisma.UserBestiaryBookmarkGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBestiaryBookmarkGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserBestiaryBookmarkCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBestiaryBookmarkCountAggregateOutputType> | number
        }
      }
    }
    UserBestiaryOrder: {
      payload: Prisma.$UserBestiaryOrderPayload<ExtArgs>
      fields: Prisma.UserBestiaryOrderFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserBestiaryOrderFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserBestiaryOrderFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        findFirst: {
          args: Prisma.UserBestiaryOrderFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserBestiaryOrderFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        findMany: {
          args: Prisma.UserBestiaryOrderFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>[]
        }
        create: {
          args: Prisma.UserBestiaryOrderCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        createMany: {
          args: Prisma.UserBestiaryOrderCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UserBestiaryOrderCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>[]
        }
        delete: {
          args: Prisma.UserBestiaryOrderDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        update: {
          args: Prisma.UserBestiaryOrderUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        deleteMany: {
          args: Prisma.UserBestiaryOrderDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserBestiaryOrderUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UserBestiaryOrderUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>[]
        }
        upsert: {
          args: Prisma.UserBestiaryOrderUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserBestiaryOrderPayload>
        }
        aggregate: {
          args: Prisma.UserBestiaryOrderAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUserBestiaryOrder>
        }
        groupBy: {
          args: Prisma.UserBestiaryOrderGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBestiaryOrderGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserBestiaryOrderCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserBestiaryOrderCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  avatar: 'avatar',
  email: 'email',
  verified: 'verified',
  bannerColor: 'bannerColor',
  globalName: 'globalName',
  supporter: 'supporter',
  joinedAt: 'joinedAt',
  secret: 'secret',
  statblockLayout: 'statblockLayout',
  statblockDesign: 'statblockDesign',
  preferredEditor: 'preferredEditor',
  unsubscribedFromEmails: 'unsubscribedFromEmails',
  SRDVersion: 'SRDVersion'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const BestiaryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  status: 'status',
  description: 'description',
  tags: 'tags',
  viewCount: 'viewCount',
  bookmarks: 'bookmarks',
  lastUpdated: 'lastUpdated'
} as const

export type BestiaryScalarFieldEnum = (typeof BestiaryScalarFieldEnum)[keyof typeof BestiaryScalarFieldEnum]


export const CreatureScalarFieldEnum = {
  id: 'id',
  bestiaryId: 'bestiaryId',
  lastUpdated: 'lastUpdated',
  stats: 'stats',
  index: 'index'
} as const

export type CreatureScalarFieldEnum = (typeof CreatureScalarFieldEnum)[keyof typeof CreatureScalarFieldEnum]


export const AutomationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  collectionId: 'collectionId',
  lastUpdated: 'lastUpdated',
  automation: 'automation'
} as const

export type AutomationScalarFieldEnum = (typeof AutomationScalarFieldEnum)[keyof typeof AutomationScalarFieldEnum]


export const AutomationCollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  status: 'status',
  lastUpdated: 'lastUpdated'
} as const

export type AutomationCollectionScalarFieldEnum = (typeof AutomationCollectionScalarFieldEnum)[keyof typeof AutomationCollectionScalarFieldEnum]


export const AutomationCollectionEditorScalarFieldEnum = {
  collectionId: 'collectionId',
  userId: 'userId'
} as const

export type AutomationCollectionEditorScalarFieldEnum = (typeof AutomationCollectionEditorScalarFieldEnum)[keyof typeof AutomationCollectionEditorScalarFieldEnum]


export const BestiaryEditorScalarFieldEnum = {
  bestiaryId: 'bestiaryId',
  userId: 'userId'
} as const

export type BestiaryEditorScalarFieldEnum = (typeof BestiaryEditorScalarFieldEnum)[keyof typeof BestiaryEditorScalarFieldEnum]


export const UserBestiaryBookmarkScalarFieldEnum = {
  userId: 'userId',
  bestiaryId: 'bestiaryId',
  createdAt: 'createdAt'
} as const

export type UserBestiaryBookmarkScalarFieldEnum = (typeof UserBestiaryBookmarkScalarFieldEnum)[keyof typeof UserBestiaryBookmarkScalarFieldEnum]


export const UserBestiaryOrderScalarFieldEnum = {
  userId: 'userId',
  bestiaryId: 'bestiaryId',
  index: 'index'
} as const

export type UserBestiaryOrderScalarFieldEnum = (typeof UserBestiaryOrderScalarFieldEnum)[keyof typeof UserBestiaryOrderScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'SupporterStatus'
 */
export type EnumSupporterStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SupporterStatus'>
    


/**
 * Reference to a field of type 'SupporterStatus[]'
 */
export type ListEnumSupporterStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SupporterStatus[]'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'StatblockLayout'
 */
export type EnumStatblockLayoutFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatblockLayout'>
    


/**
 * Reference to a field of type 'StatblockLayout[]'
 */
export type ListEnumStatblockLayoutFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatblockLayout[]'>
    


/**
 * Reference to a field of type 'StatblockDesign'
 */
export type EnumStatblockDesignFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatblockDesign'>
    


/**
 * Reference to a field of type 'StatblockDesign[]'
 */
export type ListEnumStatblockDesignFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'StatblockDesign[]'>
    


/**
 * Reference to a field of type 'Editor'
 */
export type EnumEditorFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Editor'>
    


/**
 * Reference to a field of type 'Editor[]'
 */
export type ListEnumEditorFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Editor[]'>
    


/**
 * Reference to a field of type 'SRDVersion'
 */
export type EnumSRDVersionFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SRDVersion'>
    


/**
 * Reference to a field of type 'SRDVersion[]'
 */
export type ListEnumSRDVersionFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SRDVersion[]'>
    


/**
 * Reference to a field of type 'BestiaryStatus'
 */
export type EnumBestiaryStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BestiaryStatus'>
    


/**
 * Reference to a field of type 'BestiaryStatus[]'
 */
export type ListEnumBestiaryStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BestiaryStatus[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
/**
 * Options common to all variants of `PrismaClientOptions`, regardless of whether you connect to your database through a driver adapter or through Prisma Accelerate.
 */
export interface PrismaClientBaseOptions {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}

/**
 * `PrismaClient` options for connecting to your database through Prisma Accelerate instead of a driver adapter.
 * 
 * Learn more: https://pris.ly/d/accelerate
 */
export interface PrismaClientOptionsWithAccelerateUrl extends PrismaClientBaseOptions {
  /**
   * The Prisma Accelerate connection URL. Use this option to connect to your database through Prisma Accelerate instead of using a driver adapter to connect directly.
   * 
   * Learn more: https://pris.ly/d/accelerate
   */
  accelerateUrl: string
  adapter?: never
}

/**
 * `PrismaClient` options for connecting to your database through a driver adapter. This is the common case in Prisma 7.
 * 
 * Learn more: https://pris.ly/d/driver-adapters
 */
export interface PrismaClientOptionsWithAdapter extends PrismaClientBaseOptions {
  /**
   * A driver adapter that PrismaClient uses to connect to your database, such as the ones provided by `@prisma/adapter-pg`, `@prisma/adapter-libsql`, `@prisma/adapter-planetscale`, etc.
   * 
   * A driver adapter is **required** unless you connect to your database through Prisma Accelerate (in which case use `accelerateUrl` instead).
   * 
   * Learn more: https://pris.ly/d/driver-adapters
   * 
   * @example
   * ```ts
   * import { PrismaPg } from '@prisma/adapter-pg'
   * import { PrismaClient } from './generated/prisma/client'
   * 
   * const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL })
   * const prisma = new PrismaClient({ adapter })
   * ```
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
}

/**
 * Options passed to the `PrismaClient` constructor.
 * 
 * A driver adapter (or, alternatively, a Prisma Accelerate URL) is **required**. See {@link PrismaClientOptionsWithAdapter} and {@link PrismaClientOptionsWithAccelerateUrl} for the two variants. All other properties live in {@link PrismaClientBaseOptions} and are optional.
 * 
 * Learn more about driver adapters: https://pris.ly/d/driver-adapters
 */
export type PrismaClientOptions = PrismaClientOptionsWithAccelerateUrl | PrismaClientOptionsWithAdapter
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  bestiary?: Prisma.BestiaryOmit
  creature?: Prisma.CreatureOmit
  automation?: Prisma.AutomationOmit
  automationCollection?: Prisma.AutomationCollectionOmit
  automationCollectionEditor?: Prisma.AutomationCollectionEditorOmit
  bestiaryEditor?: Prisma.BestiaryEditorOmit
  userBestiaryBookmark?: Prisma.UserBestiaryBookmarkOmit
  userBestiaryOrder?: Prisma.UserBestiaryOrderOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

