
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Bestiary: 'Bestiary',
  Creature: 'Creature',
  Automation: 'Automation',
  AutomationCollection: 'AutomationCollection',
  AutomationCollectionEditor: 'AutomationCollectionEditor',
  BestiaryEditor: 'BestiaryEditor',
  UserBestiaryBookmark: 'UserBestiaryBookmark',
  UserBestiaryOrder: 'UserBestiaryOrder'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  avatar: 'avatar',
  email: 'email',
  verified: 'verified',
  bannerColor: 'bannerColor',
  globalName: 'globalName',
  supporter: 'supporter',
  joinedAt: 'joinedAt',
  secret: 'secret',
  statblockLayout: 'statblockLayout',
  statblockDesign: 'statblockDesign',
  preferredEditor: 'preferredEditor',
  unsubscribedFromEmails: 'unsubscribedFromEmails',
  SRDVersion: 'SRDVersion'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const BestiaryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  status: 'status',
  description: 'description',
  tags: 'tags',
  viewCount: 'viewCount',
  bookmarks: 'bookmarks',
  lastUpdated: 'lastUpdated'
} as const

export type BestiaryScalarFieldEnum = (typeof BestiaryScalarFieldEnum)[keyof typeof BestiaryScalarFieldEnum]


export const CreatureScalarFieldEnum = {
  id: 'id',
  bestiaryId: 'bestiaryId',
  lastUpdated: 'lastUpdated',
  stats: 'stats',
  index: 'index'
} as const

export type CreatureScalarFieldEnum = (typeof CreatureScalarFieldEnum)[keyof typeof CreatureScalarFieldEnum]


export const AutomationScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  collectionId: 'collectionId',
  lastUpdated: 'lastUpdated',
  automation: 'automation'
} as const

export type AutomationScalarFieldEnum = (typeof AutomationScalarFieldEnum)[keyof typeof AutomationScalarFieldEnum]


export const AutomationCollectionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  status: 'status',
  lastUpdated: 'lastUpdated'
} as const

export type AutomationCollectionScalarFieldEnum = (typeof AutomationCollectionScalarFieldEnum)[keyof typeof AutomationCollectionScalarFieldEnum]


export const AutomationCollectionEditorScalarFieldEnum = {
  collectionId: 'collectionId',
  userId: 'userId'
} as const

export type AutomationCollectionEditorScalarFieldEnum = (typeof AutomationCollectionEditorScalarFieldEnum)[keyof typeof AutomationCollectionEditorScalarFieldEnum]


export const BestiaryEditorScalarFieldEnum = {
  bestiaryId: 'bestiaryId',
  userId: 'userId'
} as const

export type BestiaryEditorScalarFieldEnum = (typeof BestiaryEditorScalarFieldEnum)[keyof typeof BestiaryEditorScalarFieldEnum]


export const UserBestiaryBookmarkScalarFieldEnum = {
  userId: 'userId',
  bestiaryId: 'bestiaryId',
  createdAt: 'createdAt'
} as const

export type UserBestiaryBookmarkScalarFieldEnum = (typeof UserBestiaryBookmarkScalarFieldEnum)[keyof typeof UserBestiaryBookmarkScalarFieldEnum]


export const UserBestiaryOrderScalarFieldEnum = {
  userId: 'userId',
  bestiaryId: 'bestiaryId',
  index: 'index'
} as const

export type UserBestiaryOrderScalarFieldEnum = (typeof UserBestiaryOrderScalarFieldEnum)[keyof typeof UserBestiaryOrderScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

