
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AutomationCollectionEditor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AutomationCollectionEditor
 * 
 */
export type AutomationCollectionEditorModel = runtime.Types.Result.DefaultSelection<Prisma.$AutomationCollectionEditorPayload>

export type AggregateAutomationCollectionEditor = {
  _count: AutomationCollectionEditorCountAggregateOutputType | null
  _min: AutomationCollectionEditorMinAggregateOutputType | null
  _max: AutomationCollectionEditorMaxAggregateOutputType | null
}

export type AutomationCollectionEditorMinAggregateOutputType = {
  collectionId: string | null
  userId: string | null
}

export type AutomationCollectionEditorMaxAggregateOutputType = {
  collectionId: string | null
  userId: string | null
}

export type AutomationCollectionEditorCountAggregateOutputType = {
  collectionId: number
  userId: number
  _all: number
}


export type AutomationCollectionEditorMinAggregateInputType = {
  collectionId?: true
  userId?: true
}

export type AutomationCollectionEditorMaxAggregateInputType = {
  collectionId?: true
  userId?: true
}

export type AutomationCollectionEditorCountAggregateInputType = {
  collectionId?: true
  userId?: true
  _all?: true
}

export type AutomationCollectionEditorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AutomationCollectionEditor to aggregate.
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AutomationCollectionEditors to fetch.
   */
  orderBy?: Prisma.AutomationCollectionEditorOrderByWithRelationInput | Prisma.AutomationCollectionEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AutomationCollectionEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AutomationCollectionEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AutomationCollectionEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AutomationCollectionEditors
  **/
  _count?: true | AutomationCollectionEditorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AutomationCollectionEditorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AutomationCollectionEditorMaxAggregateInputType
}

export type GetAutomationCollectionEditorAggregateType<T extends AutomationCollectionEditorAggregateArgs> = {
      [P in keyof T & keyof AggregateAutomationCollectionEditor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAutomationCollectionEditor[P]>
    : Prisma.GetScalarType<T[P], AggregateAutomationCollectionEditor[P]>
}




export type AutomationCollectionEditorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AutomationCollectionEditorWhereInput
  orderBy?: Prisma.AutomationCollectionEditorOrderByWithAggregationInput | Prisma.AutomationCollectionEditorOrderByWithAggregationInput[]
  by: Prisma.AutomationCollectionEditorScalarFieldEnum[] | Prisma.AutomationCollectionEditorScalarFieldEnum
  having?: Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AutomationCollectionEditorCountAggregateInputType | true
  _min?: AutomationCollectionEditorMinAggregateInputType
  _max?: AutomationCollectionEditorMaxAggregateInputType
}

export type AutomationCollectionEditorGroupByOutputType = {
  collectionId: string
  userId: string
  _count: AutomationCollectionEditorCountAggregateOutputType | null
  _min: AutomationCollectionEditorMinAggregateOutputType | null
  _max: AutomationCollectionEditorMaxAggregateOutputType | null
}

export type GetAutomationCollectionEditorGroupByPayload<T extends AutomationCollectionEditorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AutomationCollectionEditorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AutomationCollectionEditorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AutomationCollectionEditorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AutomationCollectionEditorGroupByOutputType[P]>
      }
    >
  >



export type AutomationCollectionEditorWhereInput = {
  AND?: Prisma.AutomationCollectionEditorWhereInput | Prisma.AutomationCollectionEditorWhereInput[]
  OR?: Prisma.AutomationCollectionEditorWhereInput[]
  NOT?: Prisma.AutomationCollectionEditorWhereInput | Prisma.AutomationCollectionEditorWhereInput[]
  collectionId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
  userId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
  collection?: Prisma.XOR<Prisma.AutomationCollectionScalarRelationFilter, Prisma.AutomationCollectionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type AutomationCollectionEditorOrderByWithRelationInput = {
  collectionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  collection?: Prisma.AutomationCollectionOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type AutomationCollectionEditorWhereUniqueInput = Prisma.AtLeast<{
  collectionId_userId?: Prisma.AutomationCollectionEditorCollectionIdUserIdCompoundUniqueInput
  AND?: Prisma.AutomationCollectionEditorWhereInput | Prisma.AutomationCollectionEditorWhereInput[]
  OR?: Prisma.AutomationCollectionEditorWhereInput[]
  NOT?: Prisma.AutomationCollectionEditorWhereInput | Prisma.AutomationCollectionEditorWhereInput[]
  collectionId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
  userId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
  collection?: Prisma.XOR<Prisma.AutomationCollectionScalarRelationFilter, Prisma.AutomationCollectionWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "collectionId_userId">

export type AutomationCollectionEditorOrderByWithAggregationInput = {
  collectionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.AutomationCollectionEditorCountOrderByAggregateInput
  _max?: Prisma.AutomationCollectionEditorMaxOrderByAggregateInput
  _min?: Prisma.AutomationCollectionEditorMinOrderByAggregateInput
}

export type AutomationCollectionEditorScalarWhereWithAggregatesInput = {
  AND?: Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput | Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput[]
  OR?: Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput | Prisma.AutomationCollectionEditorScalarWhereWithAggregatesInput[]
  collectionId?: Prisma.StringWithAggregatesFilter<"AutomationCollectionEditor"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AutomationCollectionEditor"> | string
}

export type AutomationCollectionEditorCreateInput = {
  collection: Prisma.AutomationCollectionCreateNestedOneWithoutEditorsInput
  user: Prisma.UserCreateNestedOneWithoutEditedAutomationCollectionsInput
}

export type AutomationCollectionEditorUncheckedCreateInput = {
  collectionId: string
  userId: string
}

export type AutomationCollectionEditorUpdateInput = {
  collection?: Prisma.AutomationCollectionUpdateOneRequiredWithoutEditorsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutEditedAutomationCollectionsNestedInput
}

export type AutomationCollectionEditorUncheckedUpdateInput = {
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AutomationCollectionEditorCreateManyInput = {
  collectionId: string
  userId: string
}

export type AutomationCollectionEditorUpdateManyMutationInput = {

}

export type AutomationCollectionEditorUncheckedUpdateManyInput = {
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AutomationCollectionEditorListRelationFilter = {
  every?: Prisma.AutomationCollectionEditorWhereInput
  some?: Prisma.AutomationCollectionEditorWhereInput
  none?: Prisma.AutomationCollectionEditorWhereInput
}

export type AutomationCollectionEditorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AutomationCollectionEditorCollectionIdUserIdCompoundUniqueInput = {
  collectionId: string
  userId: string
}

export type AutomationCollectionEditorCountOrderByAggregateInput = {
  collectionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AutomationCollectionEditorMaxOrderByAggregateInput = {
  collectionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AutomationCollectionEditorMinOrderByAggregateInput = {
  collectionId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type AutomationCollectionEditorCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput> | Prisma.AutomationCollectionEditorCreateWithoutUserInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyUserInputEnvelope
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
}

export type AutomationCollectionEditorUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput> | Prisma.AutomationCollectionEditorCreateWithoutUserInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyUserInputEnvelope
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
}

export type AutomationCollectionEditorUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput> | Prisma.AutomationCollectionEditorCreateWithoutUserInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutUserInput | Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyUserInputEnvelope
  set?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  disconnect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  delete?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  update?: Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutUserInput | Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutUserInput | Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
}

export type AutomationCollectionEditorUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput> | Prisma.AutomationCollectionEditorCreateWithoutUserInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutUserInput | Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyUserInputEnvelope
  set?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  disconnect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  delete?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  update?: Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutUserInput | Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutUserInput | Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
}

export type AutomationCollectionEditorCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput> | Prisma.AutomationCollectionEditorCreateWithoutCollectionInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyCollectionInputEnvelope
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
}

export type AutomationCollectionEditorUncheckedCreateNestedManyWithoutCollectionInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput> | Prisma.AutomationCollectionEditorCreateWithoutCollectionInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyCollectionInputEnvelope
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
}

export type AutomationCollectionEditorUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput> | Prisma.AutomationCollectionEditorCreateWithoutCollectionInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutCollectionInput | Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyCollectionInputEnvelope
  set?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  disconnect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  delete?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  update?: Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutCollectionInput | Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutCollectionInput | Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
}

export type AutomationCollectionEditorUncheckedUpdateManyWithoutCollectionNestedInput = {
  create?: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput> | Prisma.AutomationCollectionEditorCreateWithoutCollectionInput[] | Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput[]
  connectOrCreate?: Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput | Prisma.AutomationCollectionEditorCreateOrConnectWithoutCollectionInput[]
  upsert?: Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutCollectionInput | Prisma.AutomationCollectionEditorUpsertWithWhereUniqueWithoutCollectionInput[]
  createMany?: Prisma.AutomationCollectionEditorCreateManyCollectionInputEnvelope
  set?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  disconnect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  delete?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  connect?: Prisma.AutomationCollectionEditorWhereUniqueInput | Prisma.AutomationCollectionEditorWhereUniqueInput[]
  update?: Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutCollectionInput | Prisma.AutomationCollectionEditorUpdateWithWhereUniqueWithoutCollectionInput[]
  updateMany?: Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutCollectionInput | Prisma.AutomationCollectionEditorUpdateManyWithWhereWithoutCollectionInput[]
  deleteMany?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
}

export type AutomationCollectionEditorCreateWithoutUserInput = {
  collection: Prisma.AutomationCollectionCreateNestedOneWithoutEditorsInput
}

export type AutomationCollectionEditorUncheckedCreateWithoutUserInput = {
  collectionId: string
}

export type AutomationCollectionEditorCreateOrConnectWithoutUserInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  create: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput>
}

export type AutomationCollectionEditorCreateManyUserInputEnvelope = {
  data: Prisma.AutomationCollectionEditorCreateManyUserInput | Prisma.AutomationCollectionEditorCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AutomationCollectionEditorUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  update: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutUserInput>
}

export type AutomationCollectionEditorUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateWithoutUserInput, Prisma.AutomationCollectionEditorUncheckedUpdateWithoutUserInput>
}

export type AutomationCollectionEditorUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AutomationCollectionEditorScalarWhereInput
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateManyMutationInput, Prisma.AutomationCollectionEditorUncheckedUpdateManyWithoutUserInput>
}

export type AutomationCollectionEditorScalarWhereInput = {
  AND?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
  OR?: Prisma.AutomationCollectionEditorScalarWhereInput[]
  NOT?: Prisma.AutomationCollectionEditorScalarWhereInput | Prisma.AutomationCollectionEditorScalarWhereInput[]
  collectionId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
  userId?: Prisma.StringFilter<"AutomationCollectionEditor"> | string
}

export type AutomationCollectionEditorCreateWithoutCollectionInput = {
  user: Prisma.UserCreateNestedOneWithoutEditedAutomationCollectionsInput
}

export type AutomationCollectionEditorUncheckedCreateWithoutCollectionInput = {
  userId: string
}

export type AutomationCollectionEditorCreateOrConnectWithoutCollectionInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  create: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput>
}

export type AutomationCollectionEditorCreateManyCollectionInputEnvelope = {
  data: Prisma.AutomationCollectionEditorCreateManyCollectionInput | Prisma.AutomationCollectionEditorCreateManyCollectionInput[]
  skipDuplicates?: boolean
}

export type AutomationCollectionEditorUpsertWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  update: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedUpdateWithoutCollectionInput>
  create: Prisma.XOR<Prisma.AutomationCollectionEditorCreateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedCreateWithoutCollectionInput>
}

export type AutomationCollectionEditorUpdateWithWhereUniqueWithoutCollectionInput = {
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateWithoutCollectionInput, Prisma.AutomationCollectionEditorUncheckedUpdateWithoutCollectionInput>
}

export type AutomationCollectionEditorUpdateManyWithWhereWithoutCollectionInput = {
  where: Prisma.AutomationCollectionEditorScalarWhereInput
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateManyMutationInput, Prisma.AutomationCollectionEditorUncheckedUpdateManyWithoutCollectionInput>
}

export type AutomationCollectionEditorCreateManyUserInput = {
  collectionId: string
}

export type AutomationCollectionEditorUpdateWithoutUserInput = {
  collection?: Prisma.AutomationCollectionUpdateOneRequiredWithoutEditorsNestedInput
}

export type AutomationCollectionEditorUncheckedUpdateWithoutUserInput = {
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AutomationCollectionEditorUncheckedUpdateManyWithoutUserInput = {
  collectionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AutomationCollectionEditorCreateManyCollectionInput = {
  userId: string
}

export type AutomationCollectionEditorUpdateWithoutCollectionInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutEditedAutomationCollectionsNestedInput
}

export type AutomationCollectionEditorUncheckedUpdateWithoutCollectionInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AutomationCollectionEditorUncheckedUpdateManyWithoutCollectionInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AutomationCollectionEditorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  collectionId?: boolean
  userId?: boolean
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["automationCollectionEditor"]>

export type AutomationCollectionEditorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  collectionId?: boolean
  userId?: boolean
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["automationCollectionEditor"]>

export type AutomationCollectionEditorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  collectionId?: boolean
  userId?: boolean
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["automationCollectionEditor"]>

export type AutomationCollectionEditorSelectScalar = {
  collectionId?: boolean
  userId?: boolean
}

export type AutomationCollectionEditorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"collectionId" | "userId", ExtArgs["result"]["automationCollectionEditor"]>
export type AutomationCollectionEditorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AutomationCollectionEditorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AutomationCollectionEditorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  collection?: boolean | Prisma.AutomationCollectionDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AutomationCollectionEditorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AutomationCollectionEditor"
  objects: {
    collection: Prisma.$AutomationCollectionPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    collectionId: string
    userId: string
  }, ExtArgs["result"]["automationCollectionEditor"]>
  composites: {}
}

export type AutomationCollectionEditorGetPayload<S extends boolean | null | undefined | AutomationCollectionEditorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload, S>

export type AutomationCollectionEditorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AutomationCollectionEditorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AutomationCollectionEditorCountAggregateInputType | true
  }

export interface AutomationCollectionEditorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AutomationCollectionEditor'], meta: { name: 'AutomationCollectionEditor' } }
  /**
   * Find zero or one AutomationCollectionEditor that matches the filter.
   * @param {AutomationCollectionEditorFindUniqueArgs} args - Arguments to find a AutomationCollectionEditor
   * @example
   * // Get one AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AutomationCollectionEditorFindUniqueArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AutomationCollectionEditor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AutomationCollectionEditorFindUniqueOrThrowArgs} args - Arguments to find a AutomationCollectionEditor
   * @example
   * // Get one AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AutomationCollectionEditorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AutomationCollectionEditor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorFindFirstArgs} args - Arguments to find a AutomationCollectionEditor
   * @example
   * // Get one AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AutomationCollectionEditorFindFirstArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorFindFirstArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AutomationCollectionEditor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorFindFirstOrThrowArgs} args - Arguments to find a AutomationCollectionEditor
   * @example
   * // Get one AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AutomationCollectionEditorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AutomationCollectionEditors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AutomationCollectionEditors
   * const automationCollectionEditors = await prisma.automationCollectionEditor.findMany()
   * 
   * // Get first 10 AutomationCollectionEditors
   * const automationCollectionEditors = await prisma.automationCollectionEditor.findMany({ take: 10 })
   * 
   * // Only select the `collectionId`
   * const automationCollectionEditorWithCollectionIdOnly = await prisma.automationCollectionEditor.findMany({ select: { collectionId: true } })
   * 
   */
  findMany<T extends AutomationCollectionEditorFindManyArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AutomationCollectionEditor.
   * @param {AutomationCollectionEditorCreateArgs} args - Arguments to create a AutomationCollectionEditor.
   * @example
   * // Create one AutomationCollectionEditor
   * const AutomationCollectionEditor = await prisma.automationCollectionEditor.create({
   *   data: {
   *     // ... data to create a AutomationCollectionEditor
   *   }
   * })
   * 
   */
  create<T extends AutomationCollectionEditorCreateArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorCreateArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AutomationCollectionEditors.
   * @param {AutomationCollectionEditorCreateManyArgs} args - Arguments to create many AutomationCollectionEditors.
   * @example
   * // Create many AutomationCollectionEditors
   * const automationCollectionEditor = await prisma.automationCollectionEditor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AutomationCollectionEditorCreateManyArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AutomationCollectionEditors and returns the data saved in the database.
   * @param {AutomationCollectionEditorCreateManyAndReturnArgs} args - Arguments to create many AutomationCollectionEditors.
   * @example
   * // Create many AutomationCollectionEditors
   * const automationCollectionEditor = await prisma.automationCollectionEditor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AutomationCollectionEditors and only return the `collectionId`
   * const automationCollectionEditorWithCollectionIdOnly = await prisma.automationCollectionEditor.createManyAndReturn({
   *   select: { collectionId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AutomationCollectionEditorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AutomationCollectionEditor.
   * @param {AutomationCollectionEditorDeleteArgs} args - Arguments to delete one AutomationCollectionEditor.
   * @example
   * // Delete one AutomationCollectionEditor
   * const AutomationCollectionEditor = await prisma.automationCollectionEditor.delete({
   *   where: {
   *     // ... filter to delete one AutomationCollectionEditor
   *   }
   * })
   * 
   */
  delete<T extends AutomationCollectionEditorDeleteArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorDeleteArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AutomationCollectionEditor.
   * @param {AutomationCollectionEditorUpdateArgs} args - Arguments to update one AutomationCollectionEditor.
   * @example
   * // Update one AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AutomationCollectionEditorUpdateArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorUpdateArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AutomationCollectionEditors.
   * @param {AutomationCollectionEditorDeleteManyArgs} args - Arguments to filter AutomationCollectionEditors to delete.
   * @example
   * // Delete a few AutomationCollectionEditors
   * const { count } = await prisma.automationCollectionEditor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AutomationCollectionEditorDeleteManyArgs>(args?: Prisma.SelectSubset<T, AutomationCollectionEditorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AutomationCollectionEditors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AutomationCollectionEditors
   * const automationCollectionEditor = await prisma.automationCollectionEditor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AutomationCollectionEditorUpdateManyArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AutomationCollectionEditors and returns the data updated in the database.
   * @param {AutomationCollectionEditorUpdateManyAndReturnArgs} args - Arguments to update many AutomationCollectionEditors.
   * @example
   * // Update many AutomationCollectionEditors
   * const automationCollectionEditor = await prisma.automationCollectionEditor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AutomationCollectionEditors and only return the `collectionId`
   * const automationCollectionEditorWithCollectionIdOnly = await prisma.automationCollectionEditor.updateManyAndReturn({
   *   select: { collectionId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AutomationCollectionEditorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AutomationCollectionEditor.
   * @param {AutomationCollectionEditorUpsertArgs} args - Arguments to update or create a AutomationCollectionEditor.
   * @example
   * // Update or create a AutomationCollectionEditor
   * const automationCollectionEditor = await prisma.automationCollectionEditor.upsert({
   *   create: {
   *     // ... data to create a AutomationCollectionEditor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AutomationCollectionEditor we want to update
   *   }
   * })
   */
  upsert<T extends AutomationCollectionEditorUpsertArgs>(args: Prisma.SelectSubset<T, AutomationCollectionEditorUpsertArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionEditorClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionEditorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AutomationCollectionEditors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorCountArgs} args - Arguments to filter AutomationCollectionEditors to count.
   * @example
   * // Count the number of AutomationCollectionEditors
   * const count = await prisma.automationCollectionEditor.count({
   *   where: {
   *     // ... the filter for the AutomationCollectionEditors we want to count
   *   }
   * })
  **/
  count<T extends AutomationCollectionEditorCountArgs>(
    args?: Prisma.Subset<T, AutomationCollectionEditorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AutomationCollectionEditorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AutomationCollectionEditor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AutomationCollectionEditorAggregateArgs>(args: Prisma.Subset<T, AutomationCollectionEditorAggregateArgs>): Prisma.PrismaPromise<GetAutomationCollectionEditorAggregateType<T>>

  /**
   * Group by AutomationCollectionEditor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AutomationCollectionEditorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AutomationCollectionEditorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AutomationCollectionEditorGroupByArgs['orderBy'] }
      : { orderBy?: AutomationCollectionEditorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AutomationCollectionEditorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAutomationCollectionEditorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AutomationCollectionEditor model
 */
readonly fields: AutomationCollectionEditorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AutomationCollectionEditor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AutomationCollectionEditorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  collection<T extends Prisma.AutomationCollectionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AutomationCollectionDefaultArgs<ExtArgs>>): Prisma.Prisma__AutomationCollectionClient<runtime.Types.Result.GetResult<Prisma.$AutomationCollectionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AutomationCollectionEditor model
 */
export interface AutomationCollectionEditorFieldRefs {
  readonly collectionId: Prisma.FieldRef<"AutomationCollectionEditor", 'String'>
  readonly userId: Prisma.FieldRef<"AutomationCollectionEditor", 'String'>
}
    

// Custom InputTypes
/**
 * AutomationCollectionEditor findUnique
 */
export type AutomationCollectionEditorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter, which AutomationCollectionEditor to fetch.
   */
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
}

/**
 * AutomationCollectionEditor findUniqueOrThrow
 */
export type AutomationCollectionEditorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter, which AutomationCollectionEditor to fetch.
   */
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
}

/**
 * AutomationCollectionEditor findFirst
 */
export type AutomationCollectionEditorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter, which AutomationCollectionEditor to fetch.
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AutomationCollectionEditors to fetch.
   */
  orderBy?: Prisma.AutomationCollectionEditorOrderByWithRelationInput | Prisma.AutomationCollectionEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AutomationCollectionEditors.
   */
  cursor?: Prisma.AutomationCollectionEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AutomationCollectionEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AutomationCollectionEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AutomationCollectionEditors.
   */
  distinct?: Prisma.AutomationCollectionEditorScalarFieldEnum | Prisma.AutomationCollectionEditorScalarFieldEnum[]
}

/**
 * AutomationCollectionEditor findFirstOrThrow
 */
export type AutomationCollectionEditorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter, which AutomationCollectionEditor to fetch.
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AutomationCollectionEditors to fetch.
   */
  orderBy?: Prisma.AutomationCollectionEditorOrderByWithRelationInput | Prisma.AutomationCollectionEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AutomationCollectionEditors.
   */
  cursor?: Prisma.AutomationCollectionEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AutomationCollectionEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AutomationCollectionEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AutomationCollectionEditors.
   */
  distinct?: Prisma.AutomationCollectionEditorScalarFieldEnum | Prisma.AutomationCollectionEditorScalarFieldEnum[]
}

/**
 * AutomationCollectionEditor findMany
 */
export type AutomationCollectionEditorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter, which AutomationCollectionEditors to fetch.
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AutomationCollectionEditors to fetch.
   */
  orderBy?: Prisma.AutomationCollectionEditorOrderByWithRelationInput | Prisma.AutomationCollectionEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AutomationCollectionEditors.
   */
  cursor?: Prisma.AutomationCollectionEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AutomationCollectionEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AutomationCollectionEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AutomationCollectionEditors.
   */
  distinct?: Prisma.AutomationCollectionEditorScalarFieldEnum | Prisma.AutomationCollectionEditorScalarFieldEnum[]
}

/**
 * AutomationCollectionEditor create
 */
export type AutomationCollectionEditorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * The data needed to create a AutomationCollectionEditor.
   */
  data: Prisma.XOR<Prisma.AutomationCollectionEditorCreateInput, Prisma.AutomationCollectionEditorUncheckedCreateInput>
}

/**
 * AutomationCollectionEditor createMany
 */
export type AutomationCollectionEditorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AutomationCollectionEditors.
   */
  data: Prisma.AutomationCollectionEditorCreateManyInput | Prisma.AutomationCollectionEditorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AutomationCollectionEditor createManyAndReturn
 */
export type AutomationCollectionEditorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * The data used to create many AutomationCollectionEditors.
   */
  data: Prisma.AutomationCollectionEditorCreateManyInput | Prisma.AutomationCollectionEditorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AutomationCollectionEditor update
 */
export type AutomationCollectionEditorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * The data needed to update a AutomationCollectionEditor.
   */
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateInput, Prisma.AutomationCollectionEditorUncheckedUpdateInput>
  /**
   * Choose, which AutomationCollectionEditor to update.
   */
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
}

/**
 * AutomationCollectionEditor updateMany
 */
export type AutomationCollectionEditorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AutomationCollectionEditors.
   */
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateManyMutationInput, Prisma.AutomationCollectionEditorUncheckedUpdateManyInput>
  /**
   * Filter which AutomationCollectionEditors to update
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * Limit how many AutomationCollectionEditors to update.
   */
  limit?: number
}

/**
 * AutomationCollectionEditor updateManyAndReturn
 */
export type AutomationCollectionEditorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * The data used to update AutomationCollectionEditors.
   */
  data: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateManyMutationInput, Prisma.AutomationCollectionEditorUncheckedUpdateManyInput>
  /**
   * Filter which AutomationCollectionEditors to update
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * Limit how many AutomationCollectionEditors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AutomationCollectionEditor upsert
 */
export type AutomationCollectionEditorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * The filter to search for the AutomationCollectionEditor to update in case it exists.
   */
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
  /**
   * In case the AutomationCollectionEditor found by the `where` argument doesn't exist, create a new AutomationCollectionEditor with this data.
   */
  create: Prisma.XOR<Prisma.AutomationCollectionEditorCreateInput, Prisma.AutomationCollectionEditorUncheckedCreateInput>
  /**
   * In case the AutomationCollectionEditor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AutomationCollectionEditorUpdateInput, Prisma.AutomationCollectionEditorUncheckedUpdateInput>
}

/**
 * AutomationCollectionEditor delete
 */
export type AutomationCollectionEditorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
  /**
   * Filter which AutomationCollectionEditor to delete.
   */
  where: Prisma.AutomationCollectionEditorWhereUniqueInput
}

/**
 * AutomationCollectionEditor deleteMany
 */
export type AutomationCollectionEditorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AutomationCollectionEditors to delete
   */
  where?: Prisma.AutomationCollectionEditorWhereInput
  /**
   * Limit how many AutomationCollectionEditors to delete.
   */
  limit?: number
}

/**
 * AutomationCollectionEditor without action
 */
export type AutomationCollectionEditorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AutomationCollectionEditor
   */
  select?: Prisma.AutomationCollectionEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AutomationCollectionEditor
   */
  omit?: Prisma.AutomationCollectionEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AutomationCollectionEditorInclude<ExtArgs> | null
}
