
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Bestiary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Bestiary
 * 
 */
export type BestiaryModel = runtime.Types.Result.DefaultSelection<Prisma.$BestiaryPayload>

export type AggregateBestiary = {
  _count: BestiaryCountAggregateOutputType | null
  _avg: BestiaryAvgAggregateOutputType | null
  _sum: BestiarySumAggregateOutputType | null
  _min: BestiaryMinAggregateOutputType | null
  _max: BestiaryMaxAggregateOutputType | null
}

export type BestiaryAvgAggregateOutputType = {
  viewCount: number | null
  bookmarks: number | null
}

export type BestiarySumAggregateOutputType = {
  viewCount: number | null
  bookmarks: number | null
}

export type BestiaryMinAggregateOutputType = {
  id: string | null
  name: string | null
  ownerId: string | null
  status: $Enums.BestiaryStatus | null
  description: string | null
  viewCount: number | null
  bookmarks: number | null
  lastUpdated: Date | null
}

export type BestiaryMaxAggregateOutputType = {
  id: string | null
  name: string | null
  ownerId: string | null
  status: $Enums.BestiaryStatus | null
  description: string | null
  viewCount: number | null
  bookmarks: number | null
  lastUpdated: Date | null
}

export type BestiaryCountAggregateOutputType = {
  id: number
  name: number
  ownerId: number
  status: number
  description: number
  tags: number
  viewCount: number
  bookmarks: number
  lastUpdated: number
  _all: number
}


export type BestiaryAvgAggregateInputType = {
  viewCount?: true
  bookmarks?: true
}

export type BestiarySumAggregateInputType = {
  viewCount?: true
  bookmarks?: true
}

export type BestiaryMinAggregateInputType = {
  id?: true
  name?: true
  ownerId?: true
  status?: true
  description?: true
  viewCount?: true
  bookmarks?: true
  lastUpdated?: true
}

export type BestiaryMaxAggregateInputType = {
  id?: true
  name?: true
  ownerId?: true
  status?: true
  description?: true
  viewCount?: true
  bookmarks?: true
  lastUpdated?: true
}

export type BestiaryCountAggregateInputType = {
  id?: true
  name?: true
  ownerId?: true
  status?: true
  description?: true
  tags?: true
  viewCount?: true
  bookmarks?: true
  lastUpdated?: true
  _all?: true
}

export type BestiaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestiary to aggregate.
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestiaries to fetch.
   */
  orderBy?: Prisma.BestiaryOrderByWithRelationInput | Prisma.BestiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Bestiaries
  **/
  _count?: true | BestiaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BestiaryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BestiarySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestiaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestiaryMaxAggregateInputType
}

export type GetBestiaryAggregateType<T extends BestiaryAggregateArgs> = {
      [P in keyof T & keyof AggregateBestiary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestiary[P]>
    : Prisma.GetScalarType<T[P], AggregateBestiary[P]>
}




export type BestiaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestiaryWhereInput
  orderBy?: Prisma.BestiaryOrderByWithAggregationInput | Prisma.BestiaryOrderByWithAggregationInput[]
  by: Prisma.BestiaryScalarFieldEnum[] | Prisma.BestiaryScalarFieldEnum
  having?: Prisma.BestiaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestiaryCountAggregateInputType | true
  _avg?: BestiaryAvgAggregateInputType
  _sum?: BestiarySumAggregateInputType
  _min?: BestiaryMinAggregateInputType
  _max?: BestiaryMaxAggregateInputType
}

export type BestiaryGroupByOutputType = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags: string[]
  viewCount: number
  bookmarks: number
  lastUpdated: Date
  _count: BestiaryCountAggregateOutputType | null
  _avg: BestiaryAvgAggregateOutputType | null
  _sum: BestiarySumAggregateOutputType | null
  _min: BestiaryMinAggregateOutputType | null
  _max: BestiaryMaxAggregateOutputType | null
}

export type GetBestiaryGroupByPayload<T extends BestiaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestiaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestiaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestiaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestiaryGroupByOutputType[P]>
      }
    >
  >



export type BestiaryWhereInput = {
  AND?: Prisma.BestiaryWhereInput | Prisma.BestiaryWhereInput[]
  OR?: Prisma.BestiaryWhereInput[]
  NOT?: Prisma.BestiaryWhereInput | Prisma.BestiaryWhereInput[]
  id?: Prisma.StringFilter<"Bestiary"> | string
  name?: Prisma.StringFilter<"Bestiary"> | string
  ownerId?: Prisma.StringFilter<"Bestiary"> | string
  status?: Prisma.EnumBestiaryStatusFilter<"Bestiary"> | $Enums.BestiaryStatus
  description?: Prisma.StringFilter<"Bestiary"> | string
  tags?: Prisma.StringNullableListFilter<"Bestiary">
  viewCount?: Prisma.IntFilter<"Bestiary"> | number
  bookmarks?: Prisma.IntFilter<"Bestiary"> | number
  lastUpdated?: Prisma.DateTimeFilter<"Bestiary"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  creatures?: Prisma.CreatureListRelationFilter
  editors?: Prisma.BestiaryEditorListRelationFilter
  bookmarkedBy?: Prisma.UserBestiaryBookmarkListRelationFilter
  orderedBy?: Prisma.UserBestiaryOrderListRelationFilter
}

export type BestiaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
  lastUpdated?: Prisma.SortOrder
  owner?: Prisma.UserOrderByWithRelationInput
  creatures?: Prisma.CreatureOrderByRelationAggregateInput
  editors?: Prisma.BestiaryEditorOrderByRelationAggregateInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkOrderByRelationAggregateInput
  orderedBy?: Prisma.UserBestiaryOrderOrderByRelationAggregateInput
}

export type BestiaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BestiaryWhereInput | Prisma.BestiaryWhereInput[]
  OR?: Prisma.BestiaryWhereInput[]
  NOT?: Prisma.BestiaryWhereInput | Prisma.BestiaryWhereInput[]
  name?: Prisma.StringFilter<"Bestiary"> | string
  ownerId?: Prisma.StringFilter<"Bestiary"> | string
  status?: Prisma.EnumBestiaryStatusFilter<"Bestiary"> | $Enums.BestiaryStatus
  description?: Prisma.StringFilter<"Bestiary"> | string
  tags?: Prisma.StringNullableListFilter<"Bestiary">
  viewCount?: Prisma.IntFilter<"Bestiary"> | number
  bookmarks?: Prisma.IntFilter<"Bestiary"> | number
  lastUpdated?: Prisma.DateTimeFilter<"Bestiary"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  creatures?: Prisma.CreatureListRelationFilter
  editors?: Prisma.BestiaryEditorListRelationFilter
  bookmarkedBy?: Prisma.UserBestiaryBookmarkListRelationFilter
  orderedBy?: Prisma.UserBestiaryOrderListRelationFilter
}, "id">

export type BestiaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
  lastUpdated?: Prisma.SortOrder
  _count?: Prisma.BestiaryCountOrderByAggregateInput
  _avg?: Prisma.BestiaryAvgOrderByAggregateInput
  _max?: Prisma.BestiaryMaxOrderByAggregateInput
  _min?: Prisma.BestiaryMinOrderByAggregateInput
  _sum?: Prisma.BestiarySumOrderByAggregateInput
}

export type BestiaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestiaryScalarWhereWithAggregatesInput | Prisma.BestiaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestiaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestiaryScalarWhereWithAggregatesInput | Prisma.BestiaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Bestiary"> | string
  name?: Prisma.StringWithAggregatesFilter<"Bestiary"> | string
  ownerId?: Prisma.StringWithAggregatesFilter<"Bestiary"> | string
  status?: Prisma.EnumBestiaryStatusWithAggregatesFilter<"Bestiary"> | $Enums.BestiaryStatus
  description?: Prisma.StringWithAggregatesFilter<"Bestiary"> | string
  tags?: Prisma.StringNullableListFilter<"Bestiary">
  viewCount?: Prisma.IntWithAggregatesFilter<"Bestiary"> | number
  bookmarks?: Prisma.IntWithAggregatesFilter<"Bestiary"> | number
  lastUpdated?: Prisma.DateTimeWithAggregatesFilter<"Bestiary"> | Date | string
}

export type BestiaryCreateInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBestiariesInput
  creatures?: Prisma.CreatureCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureUncheckedCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBestiariesNestedInput
  creatures?: Prisma.CreatureUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUncheckedUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryCreateManyInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
}

export type BestiaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BestiaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type BestiaryListRelationFilter = {
  every?: Prisma.BestiaryWhereInput
  some?: Prisma.BestiaryWhereInput
  none?: Prisma.BestiaryWhereInput
}

export type BestiaryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type BestiaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
  lastUpdated?: Prisma.SortOrder
}

export type BestiaryAvgOrderByAggregateInput = {
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
}

export type BestiaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
  lastUpdated?: Prisma.SortOrder
}

export type BestiaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
  lastUpdated?: Prisma.SortOrder
}

export type BestiarySumOrderByAggregateInput = {
  viewCount?: Prisma.SortOrder
  bookmarks?: Prisma.SortOrder
}

export type BestiaryScalarRelationFilter = {
  is?: Prisma.BestiaryWhereInput
  isNot?: Prisma.BestiaryWhereInput
}

export type BestiaryCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput> | Prisma.BestiaryCreateWithoutOwnerInput[] | Prisma.BestiaryUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOwnerInput | Prisma.BestiaryCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.BestiaryCreateManyOwnerInputEnvelope
  connect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
}

export type BestiaryUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput> | Prisma.BestiaryCreateWithoutOwnerInput[] | Prisma.BestiaryUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOwnerInput | Prisma.BestiaryCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.BestiaryCreateManyOwnerInputEnvelope
  connect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
}

export type BestiaryUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput> | Prisma.BestiaryCreateWithoutOwnerInput[] | Prisma.BestiaryUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOwnerInput | Prisma.BestiaryCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.BestiaryUpsertWithWhereUniqueWithoutOwnerInput | Prisma.BestiaryUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.BestiaryCreateManyOwnerInputEnvelope
  set?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  disconnect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  delete?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  connect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  update?: Prisma.BestiaryUpdateWithWhereUniqueWithoutOwnerInput | Prisma.BestiaryUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.BestiaryUpdateManyWithWhereWithoutOwnerInput | Prisma.BestiaryUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.BestiaryScalarWhereInput | Prisma.BestiaryScalarWhereInput[]
}

export type BestiaryUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput> | Prisma.BestiaryCreateWithoutOwnerInput[] | Prisma.BestiaryUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOwnerInput | Prisma.BestiaryCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.BestiaryUpsertWithWhereUniqueWithoutOwnerInput | Prisma.BestiaryUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.BestiaryCreateManyOwnerInputEnvelope
  set?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  disconnect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  delete?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  connect?: Prisma.BestiaryWhereUniqueInput | Prisma.BestiaryWhereUniqueInput[]
  update?: Prisma.BestiaryUpdateWithWhereUniqueWithoutOwnerInput | Prisma.BestiaryUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.BestiaryUpdateManyWithWhereWithoutOwnerInput | Prisma.BestiaryUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.BestiaryScalarWhereInput | Prisma.BestiaryScalarWhereInput[]
}

export type BestiaryCreatetagsInput = {
  set: string[]
}

export type EnumBestiaryStatusFieldUpdateOperationsInput = {
  set?: $Enums.BestiaryStatus
}

export type BestiaryUpdatetagsInput = {
  set?: string[]
  push?: string | string[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BestiaryCreateNestedOneWithoutCreaturesInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutCreaturesInput, Prisma.BestiaryUncheckedCreateWithoutCreaturesInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutCreaturesInput
  connect?: Prisma.BestiaryWhereUniqueInput
}

export type BestiaryUpdateOneRequiredWithoutCreaturesNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutCreaturesInput, Prisma.BestiaryUncheckedCreateWithoutCreaturesInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutCreaturesInput
  upsert?: Prisma.BestiaryUpsertWithoutCreaturesInput
  connect?: Prisma.BestiaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestiaryUpdateToOneWithWhereWithoutCreaturesInput, Prisma.BestiaryUpdateWithoutCreaturesInput>, Prisma.BestiaryUncheckedUpdateWithoutCreaturesInput>
}

export type BestiaryCreateNestedOneWithoutEditorsInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutEditorsInput, Prisma.BestiaryUncheckedCreateWithoutEditorsInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutEditorsInput
  connect?: Prisma.BestiaryWhereUniqueInput
}

export type BestiaryUpdateOneRequiredWithoutEditorsNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutEditorsInput, Prisma.BestiaryUncheckedCreateWithoutEditorsInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutEditorsInput
  upsert?: Prisma.BestiaryUpsertWithoutEditorsInput
  connect?: Prisma.BestiaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestiaryUpdateToOneWithWhereWithoutEditorsInput, Prisma.BestiaryUpdateWithoutEditorsInput>, Prisma.BestiaryUncheckedUpdateWithoutEditorsInput>
}

export type BestiaryCreateNestedOneWithoutBookmarkedByInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedCreateWithoutBookmarkedByInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutBookmarkedByInput
  connect?: Prisma.BestiaryWhereUniqueInput
}

export type BestiaryUpdateOneRequiredWithoutBookmarkedByNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedCreateWithoutBookmarkedByInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutBookmarkedByInput
  upsert?: Prisma.BestiaryUpsertWithoutBookmarkedByInput
  connect?: Prisma.BestiaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestiaryUpdateToOneWithWhereWithoutBookmarkedByInput, Prisma.BestiaryUpdateWithoutBookmarkedByInput>, Prisma.BestiaryUncheckedUpdateWithoutBookmarkedByInput>
}

export type BestiaryCreateNestedOneWithoutOrderedByInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOrderedByInput, Prisma.BestiaryUncheckedCreateWithoutOrderedByInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOrderedByInput
  connect?: Prisma.BestiaryWhereUniqueInput
}

export type BestiaryUpdateOneRequiredWithoutOrderedByNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryCreateWithoutOrderedByInput, Prisma.BestiaryUncheckedCreateWithoutOrderedByInput>
  connectOrCreate?: Prisma.BestiaryCreateOrConnectWithoutOrderedByInput
  upsert?: Prisma.BestiaryUpsertWithoutOrderedByInput
  connect?: Prisma.BestiaryWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BestiaryUpdateToOneWithWhereWithoutOrderedByInput, Prisma.BestiaryUpdateWithoutOrderedByInput>, Prisma.BestiaryUncheckedUpdateWithoutOrderedByInput>
}

export type BestiaryCreateWithoutOwnerInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateWithoutOwnerInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureUncheckedCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryCreateOrConnectWithoutOwnerInput = {
  where: Prisma.BestiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput>
}

export type BestiaryCreateManyOwnerInputEnvelope = {
  data: Prisma.BestiaryCreateManyOwnerInput | Prisma.BestiaryCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type BestiaryUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.BestiaryWhereUniqueInput
  update: Prisma.XOR<Prisma.BestiaryUpdateWithoutOwnerInput, Prisma.BestiaryUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutOwnerInput, Prisma.BestiaryUncheckedCreateWithoutOwnerInput>
}

export type BestiaryUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.BestiaryWhereUniqueInput
  data: Prisma.XOR<Prisma.BestiaryUpdateWithoutOwnerInput, Prisma.BestiaryUncheckedUpdateWithoutOwnerInput>
}

export type BestiaryUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.BestiaryScalarWhereInput
  data: Prisma.XOR<Prisma.BestiaryUpdateManyMutationInput, Prisma.BestiaryUncheckedUpdateManyWithoutOwnerInput>
}

export type BestiaryScalarWhereInput = {
  AND?: Prisma.BestiaryScalarWhereInput | Prisma.BestiaryScalarWhereInput[]
  OR?: Prisma.BestiaryScalarWhereInput[]
  NOT?: Prisma.BestiaryScalarWhereInput | Prisma.BestiaryScalarWhereInput[]
  id?: Prisma.StringFilter<"Bestiary"> | string
  name?: Prisma.StringFilter<"Bestiary"> | string
  ownerId?: Prisma.StringFilter<"Bestiary"> | string
  status?: Prisma.EnumBestiaryStatusFilter<"Bestiary"> | $Enums.BestiaryStatus
  description?: Prisma.StringFilter<"Bestiary"> | string
  tags?: Prisma.StringNullableListFilter<"Bestiary">
  viewCount?: Prisma.IntFilter<"Bestiary"> | number
  bookmarks?: Prisma.IntFilter<"Bestiary"> | number
  lastUpdated?: Prisma.DateTimeFilter<"Bestiary"> | Date | string
}

export type BestiaryCreateWithoutCreaturesInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBestiariesInput
  editors?: Prisma.BestiaryEditorCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateWithoutCreaturesInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  editors?: Prisma.BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryCreateOrConnectWithoutCreaturesInput = {
  where: Prisma.BestiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutCreaturesInput, Prisma.BestiaryUncheckedCreateWithoutCreaturesInput>
}

export type BestiaryUpsertWithoutCreaturesInput = {
  update: Prisma.XOR<Prisma.BestiaryUpdateWithoutCreaturesInput, Prisma.BestiaryUncheckedUpdateWithoutCreaturesInput>
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutCreaturesInput, Prisma.BestiaryUncheckedCreateWithoutCreaturesInput>
  where?: Prisma.BestiaryWhereInput
}

export type BestiaryUpdateToOneWithWhereWithoutCreaturesInput = {
  where?: Prisma.BestiaryWhereInput
  data: Prisma.XOR<Prisma.BestiaryUpdateWithoutCreaturesInput, Prisma.BestiaryUncheckedUpdateWithoutCreaturesInput>
}

export type BestiaryUpdateWithoutCreaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBestiariesNestedInput
  editors?: Prisma.BestiaryEditorUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateWithoutCreaturesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  editors?: Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryCreateWithoutEditorsInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBestiariesInput
  creatures?: Prisma.CreatureCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateWithoutEditorsInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureUncheckedCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryCreateOrConnectWithoutEditorsInput = {
  where: Prisma.BestiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutEditorsInput, Prisma.BestiaryUncheckedCreateWithoutEditorsInput>
}

export type BestiaryUpsertWithoutEditorsInput = {
  update: Prisma.XOR<Prisma.BestiaryUpdateWithoutEditorsInput, Prisma.BestiaryUncheckedUpdateWithoutEditorsInput>
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutEditorsInput, Prisma.BestiaryUncheckedCreateWithoutEditorsInput>
  where?: Prisma.BestiaryWhereInput
}

export type BestiaryUpdateToOneWithWhereWithoutEditorsInput = {
  where?: Prisma.BestiaryWhereInput
  data: Prisma.XOR<Prisma.BestiaryUpdateWithoutEditorsInput, Prisma.BestiaryUncheckedUpdateWithoutEditorsInput>
}

export type BestiaryUpdateWithoutEditorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBestiariesNestedInput
  creatures?: Prisma.CreatureUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateWithoutEditorsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUncheckedUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryCreateWithoutBookmarkedByInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBestiariesInput
  creatures?: Prisma.CreatureCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateWithoutBookmarkedByInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureUncheckedCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryCreateOrConnectWithoutBookmarkedByInput = {
  where: Prisma.BestiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedCreateWithoutBookmarkedByInput>
}

export type BestiaryUpsertWithoutBookmarkedByInput = {
  update: Prisma.XOR<Prisma.BestiaryUpdateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedUpdateWithoutBookmarkedByInput>
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedCreateWithoutBookmarkedByInput>
  where?: Prisma.BestiaryWhereInput
}

export type BestiaryUpdateToOneWithWhereWithoutBookmarkedByInput = {
  where?: Prisma.BestiaryWhereInput
  data: Prisma.XOR<Prisma.BestiaryUpdateWithoutBookmarkedByInput, Prisma.BestiaryUncheckedUpdateWithoutBookmarkedByInput>
}

export type BestiaryUpdateWithoutBookmarkedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBestiariesNestedInput
  creatures?: Prisma.CreatureUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateWithoutBookmarkedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUncheckedUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryCreateWithoutOrderedByInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutBestiariesInput
  creatures?: Prisma.CreatureCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput
}

export type BestiaryUncheckedCreateWithoutOrderedByInput = {
  id: string
  name: string
  ownerId: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
  creatures?: Prisma.CreatureUncheckedCreateNestedManyWithoutBestiaryInput
  editors?: Prisma.BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput
}

export type BestiaryCreateOrConnectWithoutOrderedByInput = {
  where: Prisma.BestiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutOrderedByInput, Prisma.BestiaryUncheckedCreateWithoutOrderedByInput>
}

export type BestiaryUpsertWithoutOrderedByInput = {
  update: Prisma.XOR<Prisma.BestiaryUpdateWithoutOrderedByInput, Prisma.BestiaryUncheckedUpdateWithoutOrderedByInput>
  create: Prisma.XOR<Prisma.BestiaryCreateWithoutOrderedByInput, Prisma.BestiaryUncheckedCreateWithoutOrderedByInput>
  where?: Prisma.BestiaryWhereInput
}

export type BestiaryUpdateToOneWithWhereWithoutOrderedByInput = {
  where?: Prisma.BestiaryWhereInput
  data: Prisma.XOR<Prisma.BestiaryUpdateWithoutOrderedByInput, Prisma.BestiaryUncheckedUpdateWithoutOrderedByInput>
}

export type BestiaryUpdateWithoutOrderedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutBestiariesNestedInput
  creatures?: Prisma.CreatureUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateWithoutOrderedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUncheckedUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryCreateManyOwnerInput = {
  id: string
  name: string
  status: $Enums.BestiaryStatus
  description: string
  tags?: Prisma.BestiaryCreatetagsInput | string[]
  viewCount?: number
  bookmarks?: number
  lastUpdated?: Date | string
}

export type BestiaryUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  creatures?: Prisma.CreatureUncheckedUpdateManyWithoutBestiaryNestedInput
  editors?: Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput
  bookmarkedBy?: Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput
  orderedBy?: Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput
}

export type BestiaryUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumBestiaryStatusFieldUpdateOperationsInput | $Enums.BestiaryStatus
  description?: Prisma.StringFieldUpdateOperationsInput | string
  tags?: Prisma.BestiaryUpdatetagsInput | string[]
  viewCount?: Prisma.IntFieldUpdateOperationsInput | number
  bookmarks?: Prisma.IntFieldUpdateOperationsInput | number
  lastUpdated?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type BestiaryCountOutputType
 */

export type BestiaryCountOutputType = {
  creatures: number
  editors: number
  bookmarkedBy: number
  orderedBy: number
}

export type BestiaryCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  creatures?: boolean | BestiaryCountOutputTypeCountCreaturesArgs
  editors?: boolean | BestiaryCountOutputTypeCountEditorsArgs
  bookmarkedBy?: boolean | BestiaryCountOutputTypeCountBookmarkedByArgs
  orderedBy?: boolean | BestiaryCountOutputTypeCountOrderedByArgs
}

/**
 * BestiaryCountOutputType without action
 */
export type BestiaryCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryCountOutputType
   */
  select?: Prisma.BestiaryCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BestiaryCountOutputType without action
 */
export type BestiaryCountOutputTypeCountCreaturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CreatureWhereInput
}

/**
 * BestiaryCountOutputType without action
 */
export type BestiaryCountOutputTypeCountEditorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestiaryEditorWhereInput
}

/**
 * BestiaryCountOutputType without action
 */
export type BestiaryCountOutputTypeCountBookmarkedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBestiaryBookmarkWhereInput
}

/**
 * BestiaryCountOutputType without action
 */
export type BestiaryCountOutputTypeCountOrderedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBestiaryOrderWhereInput
}


export type BestiarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerId?: boolean
  status?: boolean
  description?: boolean
  tags?: boolean
  viewCount?: boolean
  bookmarks?: boolean
  lastUpdated?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  creatures?: boolean | Prisma.Bestiary$creaturesArgs<ExtArgs>
  editors?: boolean | Prisma.Bestiary$editorsArgs<ExtArgs>
  bookmarkedBy?: boolean | Prisma.Bestiary$bookmarkedByArgs<ExtArgs>
  orderedBy?: boolean | Prisma.Bestiary$orderedByArgs<ExtArgs>
  _count?: boolean | Prisma.BestiaryCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiary"]>

export type BestiarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerId?: boolean
  status?: boolean
  description?: boolean
  tags?: boolean
  viewCount?: boolean
  bookmarks?: boolean
  lastUpdated?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiary"]>

export type BestiarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  ownerId?: boolean
  status?: boolean
  description?: boolean
  tags?: boolean
  viewCount?: boolean
  bookmarks?: boolean
  lastUpdated?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiary"]>

export type BestiarySelectScalar = {
  id?: boolean
  name?: boolean
  ownerId?: boolean
  status?: boolean
  description?: boolean
  tags?: boolean
  viewCount?: boolean
  bookmarks?: boolean
  lastUpdated?: boolean
}

export type BestiaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "ownerId" | "status" | "description" | "tags" | "viewCount" | "bookmarks" | "lastUpdated", ExtArgs["result"]["bestiary"]>
export type BestiaryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  creatures?: boolean | Prisma.Bestiary$creaturesArgs<ExtArgs>
  editors?: boolean | Prisma.Bestiary$editorsArgs<ExtArgs>
  bookmarkedBy?: boolean | Prisma.Bestiary$bookmarkedByArgs<ExtArgs>
  orderedBy?: boolean | Prisma.Bestiary$orderedByArgs<ExtArgs>
  _count?: boolean | Prisma.BestiaryCountOutputTypeDefaultArgs<ExtArgs>
}
export type BestiaryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BestiaryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BestiaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Bestiary"
  objects: {
    owner: Prisma.$UserPayload<ExtArgs>
    creatures: Prisma.$CreaturePayload<ExtArgs>[]
    editors: Prisma.$BestiaryEditorPayload<ExtArgs>[]
    bookmarkedBy: Prisma.$UserBestiaryBookmarkPayload<ExtArgs>[]
    orderedBy: Prisma.$UserBestiaryOrderPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    ownerId: string
    status: $Enums.BestiaryStatus
    description: string
    tags: string[]
    viewCount: number
    bookmarks: number
    lastUpdated: Date
  }, ExtArgs["result"]["bestiary"]>
  composites: {}
}

export type BestiaryGetPayload<S extends boolean | null | undefined | BestiaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestiaryPayload, S>

export type BestiaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestiaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestiaryCountAggregateInputType | true
  }

export interface BestiaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Bestiary'], meta: { name: 'Bestiary' } }
  /**
   * Find zero or one Bestiary that matches the filter.
   * @param {BestiaryFindUniqueArgs} args - Arguments to find a Bestiary
   * @example
   * // Get one Bestiary
   * const bestiary = await prisma.bestiary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestiaryFindUniqueArgs>(args: Prisma.SelectSubset<T, BestiaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Bestiary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestiaryFindUniqueOrThrowArgs} args - Arguments to find a Bestiary
   * @example
   * // Get one Bestiary
   * const bestiary = await prisma.bestiary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestiaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestiaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestiary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryFindFirstArgs} args - Arguments to find a Bestiary
   * @example
   * // Get one Bestiary
   * const bestiary = await prisma.bestiary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestiaryFindFirstArgs>(args?: Prisma.SelectSubset<T, BestiaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Bestiary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryFindFirstOrThrowArgs} args - Arguments to find a Bestiary
   * @example
   * // Get one Bestiary
   * const bestiary = await prisma.bestiary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestiaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestiaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Bestiaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Bestiaries
   * const bestiaries = await prisma.bestiary.findMany()
   * 
   * // Get first 10 Bestiaries
   * const bestiaries = await prisma.bestiary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const bestiaryWithIdOnly = await prisma.bestiary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BestiaryFindManyArgs>(args?: Prisma.SelectSubset<T, BestiaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Bestiary.
   * @param {BestiaryCreateArgs} args - Arguments to create a Bestiary.
   * @example
   * // Create one Bestiary
   * const Bestiary = await prisma.bestiary.create({
   *   data: {
   *     // ... data to create a Bestiary
   *   }
   * })
   * 
   */
  create<T extends BestiaryCreateArgs>(args: Prisma.SelectSubset<T, BestiaryCreateArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Bestiaries.
   * @param {BestiaryCreateManyArgs} args - Arguments to create many Bestiaries.
   * @example
   * // Create many Bestiaries
   * const bestiary = await prisma.bestiary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestiaryCreateManyArgs>(args?: Prisma.SelectSubset<T, BestiaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Bestiaries and returns the data saved in the database.
   * @param {BestiaryCreateManyAndReturnArgs} args - Arguments to create many Bestiaries.
   * @example
   * // Create many Bestiaries
   * const bestiary = await prisma.bestiary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Bestiaries and only return the `id`
   * const bestiaryWithIdOnly = await prisma.bestiary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestiaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestiaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Bestiary.
   * @param {BestiaryDeleteArgs} args - Arguments to delete one Bestiary.
   * @example
   * // Delete one Bestiary
   * const Bestiary = await prisma.bestiary.delete({
   *   where: {
   *     // ... filter to delete one Bestiary
   *   }
   * })
   * 
   */
  delete<T extends BestiaryDeleteArgs>(args: Prisma.SelectSubset<T, BestiaryDeleteArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Bestiary.
   * @param {BestiaryUpdateArgs} args - Arguments to update one Bestiary.
   * @example
   * // Update one Bestiary
   * const bestiary = await prisma.bestiary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestiaryUpdateArgs>(args: Prisma.SelectSubset<T, BestiaryUpdateArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Bestiaries.
   * @param {BestiaryDeleteManyArgs} args - Arguments to filter Bestiaries to delete.
   * @example
   * // Delete a few Bestiaries
   * const { count } = await prisma.bestiary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestiaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestiaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestiaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Bestiaries
   * const bestiary = await prisma.bestiary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestiaryUpdateManyArgs>(args: Prisma.SelectSubset<T, BestiaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Bestiaries and returns the data updated in the database.
   * @param {BestiaryUpdateManyAndReturnArgs} args - Arguments to update many Bestiaries.
   * @example
   * // Update many Bestiaries
   * const bestiary = await prisma.bestiary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Bestiaries and only return the `id`
   * const bestiaryWithIdOnly = await prisma.bestiary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestiaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestiaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Bestiary.
   * @param {BestiaryUpsertArgs} args - Arguments to update or create a Bestiary.
   * @example
   * // Update or create a Bestiary
   * const bestiary = await prisma.bestiary.upsert({
   *   create: {
   *     // ... data to create a Bestiary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Bestiary we want to update
   *   }
   * })
   */
  upsert<T extends BestiaryUpsertArgs>(args: Prisma.SelectSubset<T, BestiaryUpsertArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Bestiaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryCountArgs} args - Arguments to filter Bestiaries to count.
   * @example
   * // Count the number of Bestiaries
   * const count = await prisma.bestiary.count({
   *   where: {
   *     // ... the filter for the Bestiaries we want to count
   *   }
   * })
  **/
  count<T extends BestiaryCountArgs>(
    args?: Prisma.Subset<T, BestiaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestiaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Bestiary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestiaryAggregateArgs>(args: Prisma.Subset<T, BestiaryAggregateArgs>): Prisma.PrismaPromise<GetBestiaryAggregateType<T>>

  /**
   * Group by Bestiary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestiaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestiaryGroupByArgs['orderBy'] }
      : { orderBy?: BestiaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestiaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestiaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Bestiary model
 */
readonly fields: BestiaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Bestiary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestiaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  creatures<T extends Prisma.Bestiary$creaturesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bestiary$creaturesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CreaturePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  editors<T extends Prisma.Bestiary$editorsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bestiary$editorsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  bookmarkedBy<T extends Prisma.Bestiary$bookmarkedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bestiary$bookmarkedByArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  orderedBy<T extends Prisma.Bestiary$orderedByArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Bestiary$orderedByArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Bestiary model
 */
export interface BestiaryFieldRefs {
  readonly id: Prisma.FieldRef<"Bestiary", 'String'>
  readonly name: Prisma.FieldRef<"Bestiary", 'String'>
  readonly ownerId: Prisma.FieldRef<"Bestiary", 'String'>
  readonly status: Prisma.FieldRef<"Bestiary", 'BestiaryStatus'>
  readonly description: Prisma.FieldRef<"Bestiary", 'String'>
  readonly tags: Prisma.FieldRef<"Bestiary", 'String[]'>
  readonly viewCount: Prisma.FieldRef<"Bestiary", 'Int'>
  readonly bookmarks: Prisma.FieldRef<"Bestiary", 'Int'>
  readonly lastUpdated: Prisma.FieldRef<"Bestiary", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Bestiary findUnique
 */
export type BestiaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter, which Bestiary to fetch.
   */
  where: Prisma.BestiaryWhereUniqueInput
}

/**
 * Bestiary findUniqueOrThrow
 */
export type BestiaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter, which Bestiary to fetch.
   */
  where: Prisma.BestiaryWhereUniqueInput
}

/**
 * Bestiary findFirst
 */
export type BestiaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter, which Bestiary to fetch.
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestiaries to fetch.
   */
  orderBy?: Prisma.BestiaryOrderByWithRelationInput | Prisma.BestiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestiaries.
   */
  cursor?: Prisma.BestiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestiaries.
   */
  distinct?: Prisma.BestiaryScalarFieldEnum | Prisma.BestiaryScalarFieldEnum[]
}

/**
 * Bestiary findFirstOrThrow
 */
export type BestiaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter, which Bestiary to fetch.
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestiaries to fetch.
   */
  orderBy?: Prisma.BestiaryOrderByWithRelationInput | Prisma.BestiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Bestiaries.
   */
  cursor?: Prisma.BestiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestiaries.
   */
  distinct?: Prisma.BestiaryScalarFieldEnum | Prisma.BestiaryScalarFieldEnum[]
}

/**
 * Bestiary findMany
 */
export type BestiaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter, which Bestiaries to fetch.
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Bestiaries to fetch.
   */
  orderBy?: Prisma.BestiaryOrderByWithRelationInput | Prisma.BestiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Bestiaries.
   */
  cursor?: Prisma.BestiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Bestiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Bestiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Bestiaries.
   */
  distinct?: Prisma.BestiaryScalarFieldEnum | Prisma.BestiaryScalarFieldEnum[]
}

/**
 * Bestiary create
 */
export type BestiaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * The data needed to create a Bestiary.
   */
  data: Prisma.XOR<Prisma.BestiaryCreateInput, Prisma.BestiaryUncheckedCreateInput>
}

/**
 * Bestiary createMany
 */
export type BestiaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Bestiaries.
   */
  data: Prisma.BestiaryCreateManyInput | Prisma.BestiaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Bestiary createManyAndReturn
 */
export type BestiaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * The data used to create many Bestiaries.
   */
  data: Prisma.BestiaryCreateManyInput | Prisma.BestiaryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Bestiary update
 */
export type BestiaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * The data needed to update a Bestiary.
   */
  data: Prisma.XOR<Prisma.BestiaryUpdateInput, Prisma.BestiaryUncheckedUpdateInput>
  /**
   * Choose, which Bestiary to update.
   */
  where: Prisma.BestiaryWhereUniqueInput
}

/**
 * Bestiary updateMany
 */
export type BestiaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Bestiaries.
   */
  data: Prisma.XOR<Prisma.BestiaryUpdateManyMutationInput, Prisma.BestiaryUncheckedUpdateManyInput>
  /**
   * Filter which Bestiaries to update
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * Limit how many Bestiaries to update.
   */
  limit?: number
}

/**
 * Bestiary updateManyAndReturn
 */
export type BestiaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * The data used to update Bestiaries.
   */
  data: Prisma.XOR<Prisma.BestiaryUpdateManyMutationInput, Prisma.BestiaryUncheckedUpdateManyInput>
  /**
   * Filter which Bestiaries to update
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * Limit how many Bestiaries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Bestiary upsert
 */
export type BestiaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * The filter to search for the Bestiary to update in case it exists.
   */
  where: Prisma.BestiaryWhereUniqueInput
  /**
   * In case the Bestiary found by the `where` argument doesn't exist, create a new Bestiary with this data.
   */
  create: Prisma.XOR<Prisma.BestiaryCreateInput, Prisma.BestiaryUncheckedCreateInput>
  /**
   * In case the Bestiary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestiaryUpdateInput, Prisma.BestiaryUncheckedUpdateInput>
}

/**
 * Bestiary delete
 */
export type BestiaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
  /**
   * Filter which Bestiary to delete.
   */
  where: Prisma.BestiaryWhereUniqueInput
}

/**
 * Bestiary deleteMany
 */
export type BestiaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Bestiaries to delete
   */
  where?: Prisma.BestiaryWhereInput
  /**
   * Limit how many Bestiaries to delete.
   */
  limit?: number
}

/**
 * Bestiary.creatures
 */
export type Bestiary$creaturesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Creature
   */
  select?: Prisma.CreatureSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Creature
   */
  omit?: Prisma.CreatureOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CreatureInclude<ExtArgs> | null
  where?: Prisma.CreatureWhereInput
  orderBy?: Prisma.CreatureOrderByWithRelationInput | Prisma.CreatureOrderByWithRelationInput[]
  cursor?: Prisma.CreatureWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CreatureScalarFieldEnum | Prisma.CreatureScalarFieldEnum[]
}

/**
 * Bestiary.editors
 */
export type Bestiary$editorsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  where?: Prisma.BestiaryEditorWhereInput
  orderBy?: Prisma.BestiaryEditorOrderByWithRelationInput | Prisma.BestiaryEditorOrderByWithRelationInput[]
  cursor?: Prisma.BestiaryEditorWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.BestiaryEditorScalarFieldEnum | Prisma.BestiaryEditorScalarFieldEnum[]
}

/**
 * Bestiary.bookmarkedBy
 */
export type Bestiary$bookmarkedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  where?: Prisma.UserBestiaryBookmarkWhereInput
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithRelationInput | Prisma.UserBestiaryBookmarkOrderByWithRelationInput[]
  cursor?: Prisma.UserBestiaryBookmarkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserBestiaryBookmarkScalarFieldEnum | Prisma.UserBestiaryBookmarkScalarFieldEnum[]
}

/**
 * Bestiary.orderedBy
 */
export type Bestiary$orderedByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  where?: Prisma.UserBestiaryOrderWhereInput
  orderBy?: Prisma.UserBestiaryOrderOrderByWithRelationInput | Prisma.UserBestiaryOrderOrderByWithRelationInput[]
  cursor?: Prisma.UserBestiaryOrderWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UserBestiaryOrderScalarFieldEnum | Prisma.UserBestiaryOrderScalarFieldEnum[]
}

/**
 * Bestiary without action
 */
export type BestiaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Bestiary
   */
  select?: Prisma.BestiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Bestiary
   */
  omit?: Prisma.BestiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryInclude<ExtArgs> | null
}
