
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BestiaryEditor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BestiaryEditor
 * 
 */
export type BestiaryEditorModel = runtime.Types.Result.DefaultSelection<Prisma.$BestiaryEditorPayload>

export type AggregateBestiaryEditor = {
  _count: BestiaryEditorCountAggregateOutputType | null
  _min: BestiaryEditorMinAggregateOutputType | null
  _max: BestiaryEditorMaxAggregateOutputType | null
}

export type BestiaryEditorMinAggregateOutputType = {
  bestiaryId: string | null
  userId: string | null
}

export type BestiaryEditorMaxAggregateOutputType = {
  bestiaryId: string | null
  userId: string | null
}

export type BestiaryEditorCountAggregateOutputType = {
  bestiaryId: number
  userId: number
  _all: number
}


export type BestiaryEditorMinAggregateInputType = {
  bestiaryId?: true
  userId?: true
}

export type BestiaryEditorMaxAggregateInputType = {
  bestiaryId?: true
  userId?: true
}

export type BestiaryEditorCountAggregateInputType = {
  bestiaryId?: true
  userId?: true
  _all?: true
}

export type BestiaryEditorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestiaryEditor to aggregate.
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestiaryEditors to fetch.
   */
  orderBy?: Prisma.BestiaryEditorOrderByWithRelationInput | Prisma.BestiaryEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BestiaryEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestiaryEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestiaryEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BestiaryEditors
  **/
  _count?: true | BestiaryEditorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BestiaryEditorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BestiaryEditorMaxAggregateInputType
}

export type GetBestiaryEditorAggregateType<T extends BestiaryEditorAggregateArgs> = {
      [P in keyof T & keyof AggregateBestiaryEditor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBestiaryEditor[P]>
    : Prisma.GetScalarType<T[P], AggregateBestiaryEditor[P]>
}




export type BestiaryEditorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BestiaryEditorWhereInput
  orderBy?: Prisma.BestiaryEditorOrderByWithAggregationInput | Prisma.BestiaryEditorOrderByWithAggregationInput[]
  by: Prisma.BestiaryEditorScalarFieldEnum[] | Prisma.BestiaryEditorScalarFieldEnum
  having?: Prisma.BestiaryEditorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BestiaryEditorCountAggregateInputType | true
  _min?: BestiaryEditorMinAggregateInputType
  _max?: BestiaryEditorMaxAggregateInputType
}

export type BestiaryEditorGroupByOutputType = {
  bestiaryId: string
  userId: string
  _count: BestiaryEditorCountAggregateOutputType | null
  _min: BestiaryEditorMinAggregateOutputType | null
  _max: BestiaryEditorMaxAggregateOutputType | null
}

export type GetBestiaryEditorGroupByPayload<T extends BestiaryEditorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BestiaryEditorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BestiaryEditorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BestiaryEditorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BestiaryEditorGroupByOutputType[P]>
      }
    >
  >



export type BestiaryEditorWhereInput = {
  AND?: Prisma.BestiaryEditorWhereInput | Prisma.BestiaryEditorWhereInput[]
  OR?: Prisma.BestiaryEditorWhereInput[]
  NOT?: Prisma.BestiaryEditorWhereInput | Prisma.BestiaryEditorWhereInput[]
  bestiaryId?: Prisma.StringFilter<"BestiaryEditor"> | string
  userId?: Prisma.StringFilter<"BestiaryEditor"> | string
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type BestiaryEditorOrderByWithRelationInput = {
  bestiaryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  bestiary?: Prisma.BestiaryOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type BestiaryEditorWhereUniqueInput = Prisma.AtLeast<{
  bestiaryId_userId?: Prisma.BestiaryEditorBestiaryIdUserIdCompoundUniqueInput
  AND?: Prisma.BestiaryEditorWhereInput | Prisma.BestiaryEditorWhereInput[]
  OR?: Prisma.BestiaryEditorWhereInput[]
  NOT?: Prisma.BestiaryEditorWhereInput | Prisma.BestiaryEditorWhereInput[]
  bestiaryId?: Prisma.StringFilter<"BestiaryEditor"> | string
  userId?: Prisma.StringFilter<"BestiaryEditor"> | string
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "bestiaryId_userId">

export type BestiaryEditorOrderByWithAggregationInput = {
  bestiaryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.BestiaryEditorCountOrderByAggregateInput
  _max?: Prisma.BestiaryEditorMaxOrderByAggregateInput
  _min?: Prisma.BestiaryEditorMinOrderByAggregateInput
}

export type BestiaryEditorScalarWhereWithAggregatesInput = {
  AND?: Prisma.BestiaryEditorScalarWhereWithAggregatesInput | Prisma.BestiaryEditorScalarWhereWithAggregatesInput[]
  OR?: Prisma.BestiaryEditorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BestiaryEditorScalarWhereWithAggregatesInput | Prisma.BestiaryEditorScalarWhereWithAggregatesInput[]
  bestiaryId?: Prisma.StringWithAggregatesFilter<"BestiaryEditor"> | string
  userId?: Prisma.StringWithAggregatesFilter<"BestiaryEditor"> | string
}

export type BestiaryEditorCreateInput = {
  bestiary: Prisma.BestiaryCreateNestedOneWithoutEditorsInput
  user: Prisma.UserCreateNestedOneWithoutEditedInInput
}

export type BestiaryEditorUncheckedCreateInput = {
  bestiaryId: string
  userId: string
}

export type BestiaryEditorUpdateInput = {
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutEditorsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutEditedInNestedInput
}

export type BestiaryEditorUncheckedUpdateInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BestiaryEditorCreateManyInput = {
  bestiaryId: string
  userId: string
}

export type BestiaryEditorUpdateManyMutationInput = {

}

export type BestiaryEditorUncheckedUpdateManyInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BestiaryEditorListRelationFilter = {
  every?: Prisma.BestiaryEditorWhereInput
  some?: Prisma.BestiaryEditorWhereInput
  none?: Prisma.BestiaryEditorWhereInput
}

export type BestiaryEditorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BestiaryEditorBestiaryIdUserIdCompoundUniqueInput = {
  bestiaryId: string
  userId: string
}

export type BestiaryEditorCountOrderByAggregateInput = {
  bestiaryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BestiaryEditorMaxOrderByAggregateInput = {
  bestiaryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BestiaryEditorMinOrderByAggregateInput = {
  bestiaryId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type BestiaryEditorCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput> | Prisma.BestiaryEditorCreateWithoutUserInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutUserInput | Prisma.BestiaryEditorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BestiaryEditorCreateManyUserInputEnvelope
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
}

export type BestiaryEditorUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput> | Prisma.BestiaryEditorCreateWithoutUserInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutUserInput | Prisma.BestiaryEditorCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.BestiaryEditorCreateManyUserInputEnvelope
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
}

export type BestiaryEditorUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput> | Prisma.BestiaryEditorCreateWithoutUserInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutUserInput | Prisma.BestiaryEditorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutUserInput | Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BestiaryEditorCreateManyUserInputEnvelope
  set?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  disconnect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  delete?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  update?: Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutUserInput | Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BestiaryEditorUpdateManyWithWhereWithoutUserInput | Prisma.BestiaryEditorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
}

export type BestiaryEditorUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput> | Prisma.BestiaryEditorCreateWithoutUserInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutUserInput | Prisma.BestiaryEditorCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutUserInput | Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.BestiaryEditorCreateManyUserInputEnvelope
  set?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  disconnect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  delete?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  update?: Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutUserInput | Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.BestiaryEditorUpdateManyWithWhereWithoutUserInput | Prisma.BestiaryEditorUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
}

export type BestiaryEditorCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput> | Prisma.BestiaryEditorCreateWithoutBestiaryInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput | Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.BestiaryEditorCreateManyBestiaryInputEnvelope
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
}

export type BestiaryEditorUncheckedCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput> | Prisma.BestiaryEditorCreateWithoutBestiaryInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput | Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.BestiaryEditorCreateManyBestiaryInputEnvelope
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
}

export type BestiaryEditorUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput> | Prisma.BestiaryEditorCreateWithoutBestiaryInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput | Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.BestiaryEditorCreateManyBestiaryInputEnvelope
  set?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  disconnect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  delete?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  update?: Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.BestiaryEditorUpdateManyWithWhereWithoutBestiaryInput | Prisma.BestiaryEditorUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
}

export type BestiaryEditorUncheckedUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput> | Prisma.BestiaryEditorCreateWithoutBestiaryInput[] | Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput | Prisma.BestiaryEditorCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.BestiaryEditorUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.BestiaryEditorCreateManyBestiaryInputEnvelope
  set?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  disconnect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  delete?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  connect?: Prisma.BestiaryEditorWhereUniqueInput | Prisma.BestiaryEditorWhereUniqueInput[]
  update?: Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.BestiaryEditorUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.BestiaryEditorUpdateManyWithWhereWithoutBestiaryInput | Prisma.BestiaryEditorUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
}

export type BestiaryEditorCreateWithoutUserInput = {
  bestiary: Prisma.BestiaryCreateNestedOneWithoutEditorsInput
}

export type BestiaryEditorUncheckedCreateWithoutUserInput = {
  bestiaryId: string
}

export type BestiaryEditorCreateOrConnectWithoutUserInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput>
}

export type BestiaryEditorCreateManyUserInputEnvelope = {
  data: Prisma.BestiaryEditorCreateManyUserInput | Prisma.BestiaryEditorCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type BestiaryEditorUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  update: Prisma.XOR<Prisma.BestiaryEditorUpdateWithoutUserInput, Prisma.BestiaryEditorUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutUserInput, Prisma.BestiaryEditorUncheckedCreateWithoutUserInput>
}

export type BestiaryEditorUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateWithoutUserInput, Prisma.BestiaryEditorUncheckedUpdateWithoutUserInput>
}

export type BestiaryEditorUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.BestiaryEditorScalarWhereInput
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateManyMutationInput, Prisma.BestiaryEditorUncheckedUpdateManyWithoutUserInput>
}

export type BestiaryEditorScalarWhereInput = {
  AND?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
  OR?: Prisma.BestiaryEditorScalarWhereInput[]
  NOT?: Prisma.BestiaryEditorScalarWhereInput | Prisma.BestiaryEditorScalarWhereInput[]
  bestiaryId?: Prisma.StringFilter<"BestiaryEditor"> | string
  userId?: Prisma.StringFilter<"BestiaryEditor"> | string
}

export type BestiaryEditorCreateWithoutBestiaryInput = {
  user: Prisma.UserCreateNestedOneWithoutEditedInInput
}

export type BestiaryEditorUncheckedCreateWithoutBestiaryInput = {
  userId: string
}

export type BestiaryEditorCreateOrConnectWithoutBestiaryInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  create: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput>
}

export type BestiaryEditorCreateManyBestiaryInputEnvelope = {
  data: Prisma.BestiaryEditorCreateManyBestiaryInput | Prisma.BestiaryEditorCreateManyBestiaryInput[]
  skipDuplicates?: boolean
}

export type BestiaryEditorUpsertWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  update: Prisma.XOR<Prisma.BestiaryEditorUpdateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedUpdateWithoutBestiaryInput>
  create: Prisma.XOR<Prisma.BestiaryEditorCreateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedCreateWithoutBestiaryInput>
}

export type BestiaryEditorUpdateWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.BestiaryEditorWhereUniqueInput
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateWithoutBestiaryInput, Prisma.BestiaryEditorUncheckedUpdateWithoutBestiaryInput>
}

export type BestiaryEditorUpdateManyWithWhereWithoutBestiaryInput = {
  where: Prisma.BestiaryEditorScalarWhereInput
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateManyMutationInput, Prisma.BestiaryEditorUncheckedUpdateManyWithoutBestiaryInput>
}

export type BestiaryEditorCreateManyUserInput = {
  bestiaryId: string
}

export type BestiaryEditorUpdateWithoutUserInput = {
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutEditorsNestedInput
}

export type BestiaryEditorUncheckedUpdateWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BestiaryEditorUncheckedUpdateManyWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BestiaryEditorCreateManyBestiaryInput = {
  userId: string
}

export type BestiaryEditorUpdateWithoutBestiaryInput = {
  user?: Prisma.UserUpdateOneRequiredWithoutEditedInNestedInput
}

export type BestiaryEditorUncheckedUpdateWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BestiaryEditorUncheckedUpdateManyWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type BestiaryEditorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bestiaryId?: boolean
  userId?: boolean
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiaryEditor"]>

export type BestiaryEditorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bestiaryId?: boolean
  userId?: boolean
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiaryEditor"]>

export type BestiaryEditorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  bestiaryId?: boolean
  userId?: boolean
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["bestiaryEditor"]>

export type BestiaryEditorSelectScalar = {
  bestiaryId?: boolean
  userId?: boolean
}

export type BestiaryEditorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"bestiaryId" | "userId", ExtArgs["result"]["bestiaryEditor"]>
export type BestiaryEditorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BestiaryEditorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type BestiaryEditorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $BestiaryEditorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BestiaryEditor"
  objects: {
    bestiary: Prisma.$BestiaryPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    bestiaryId: string
    userId: string
  }, ExtArgs["result"]["bestiaryEditor"]>
  composites: {}
}

export type BestiaryEditorGetPayload<S extends boolean | null | undefined | BestiaryEditorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload, S>

export type BestiaryEditorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BestiaryEditorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BestiaryEditorCountAggregateInputType | true
  }

export interface BestiaryEditorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BestiaryEditor'], meta: { name: 'BestiaryEditor' } }
  /**
   * Find zero or one BestiaryEditor that matches the filter.
   * @param {BestiaryEditorFindUniqueArgs} args - Arguments to find a BestiaryEditor
   * @example
   * // Get one BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BestiaryEditorFindUniqueArgs>(args: Prisma.SelectSubset<T, BestiaryEditorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BestiaryEditor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BestiaryEditorFindUniqueOrThrowArgs} args - Arguments to find a BestiaryEditor
   * @example
   * // Get one BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BestiaryEditorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BestiaryEditorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestiaryEditor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorFindFirstArgs} args - Arguments to find a BestiaryEditor
   * @example
   * // Get one BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BestiaryEditorFindFirstArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorFindFirstArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BestiaryEditor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorFindFirstOrThrowArgs} args - Arguments to find a BestiaryEditor
   * @example
   * // Get one BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BestiaryEditorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BestiaryEditors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BestiaryEditors
   * const bestiaryEditors = await prisma.bestiaryEditor.findMany()
   * 
   * // Get first 10 BestiaryEditors
   * const bestiaryEditors = await prisma.bestiaryEditor.findMany({ take: 10 })
   * 
   * // Only select the `bestiaryId`
   * const bestiaryEditorWithBestiaryIdOnly = await prisma.bestiaryEditor.findMany({ select: { bestiaryId: true } })
   * 
   */
  findMany<T extends BestiaryEditorFindManyArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BestiaryEditor.
   * @param {BestiaryEditorCreateArgs} args - Arguments to create a BestiaryEditor.
   * @example
   * // Create one BestiaryEditor
   * const BestiaryEditor = await prisma.bestiaryEditor.create({
   *   data: {
   *     // ... data to create a BestiaryEditor
   *   }
   * })
   * 
   */
  create<T extends BestiaryEditorCreateArgs>(args: Prisma.SelectSubset<T, BestiaryEditorCreateArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BestiaryEditors.
   * @param {BestiaryEditorCreateManyArgs} args - Arguments to create many BestiaryEditors.
   * @example
   * // Create many BestiaryEditors
   * const bestiaryEditor = await prisma.bestiaryEditor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BestiaryEditorCreateManyArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BestiaryEditors and returns the data saved in the database.
   * @param {BestiaryEditorCreateManyAndReturnArgs} args - Arguments to create many BestiaryEditors.
   * @example
   * // Create many BestiaryEditors
   * const bestiaryEditor = await prisma.bestiaryEditor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BestiaryEditors and only return the `bestiaryId`
   * const bestiaryEditorWithBestiaryIdOnly = await prisma.bestiaryEditor.createManyAndReturn({
   *   select: { bestiaryId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BestiaryEditorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BestiaryEditor.
   * @param {BestiaryEditorDeleteArgs} args - Arguments to delete one BestiaryEditor.
   * @example
   * // Delete one BestiaryEditor
   * const BestiaryEditor = await prisma.bestiaryEditor.delete({
   *   where: {
   *     // ... filter to delete one BestiaryEditor
   *   }
   * })
   * 
   */
  delete<T extends BestiaryEditorDeleteArgs>(args: Prisma.SelectSubset<T, BestiaryEditorDeleteArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BestiaryEditor.
   * @param {BestiaryEditorUpdateArgs} args - Arguments to update one BestiaryEditor.
   * @example
   * // Update one BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BestiaryEditorUpdateArgs>(args: Prisma.SelectSubset<T, BestiaryEditorUpdateArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BestiaryEditors.
   * @param {BestiaryEditorDeleteManyArgs} args - Arguments to filter BestiaryEditors to delete.
   * @example
   * // Delete a few BestiaryEditors
   * const { count } = await prisma.bestiaryEditor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BestiaryEditorDeleteManyArgs>(args?: Prisma.SelectSubset<T, BestiaryEditorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestiaryEditors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BestiaryEditors
   * const bestiaryEditor = await prisma.bestiaryEditor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BestiaryEditorUpdateManyArgs>(args: Prisma.SelectSubset<T, BestiaryEditorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BestiaryEditors and returns the data updated in the database.
   * @param {BestiaryEditorUpdateManyAndReturnArgs} args - Arguments to update many BestiaryEditors.
   * @example
   * // Update many BestiaryEditors
   * const bestiaryEditor = await prisma.bestiaryEditor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BestiaryEditors and only return the `bestiaryId`
   * const bestiaryEditorWithBestiaryIdOnly = await prisma.bestiaryEditor.updateManyAndReturn({
   *   select: { bestiaryId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BestiaryEditorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BestiaryEditorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BestiaryEditor.
   * @param {BestiaryEditorUpsertArgs} args - Arguments to update or create a BestiaryEditor.
   * @example
   * // Update or create a BestiaryEditor
   * const bestiaryEditor = await prisma.bestiaryEditor.upsert({
   *   create: {
   *     // ... data to create a BestiaryEditor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BestiaryEditor we want to update
   *   }
   * })
   */
  upsert<T extends BestiaryEditorUpsertArgs>(args: Prisma.SelectSubset<T, BestiaryEditorUpsertArgs<ExtArgs>>): Prisma.Prisma__BestiaryEditorClient<runtime.Types.Result.GetResult<Prisma.$BestiaryEditorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BestiaryEditors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorCountArgs} args - Arguments to filter BestiaryEditors to count.
   * @example
   * // Count the number of BestiaryEditors
   * const count = await prisma.bestiaryEditor.count({
   *   where: {
   *     // ... the filter for the BestiaryEditors we want to count
   *   }
   * })
  **/
  count<T extends BestiaryEditorCountArgs>(
    args?: Prisma.Subset<T, BestiaryEditorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BestiaryEditorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BestiaryEditor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BestiaryEditorAggregateArgs>(args: Prisma.Subset<T, BestiaryEditorAggregateArgs>): Prisma.PrismaPromise<GetBestiaryEditorAggregateType<T>>

  /**
   * Group by BestiaryEditor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BestiaryEditorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BestiaryEditorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BestiaryEditorGroupByArgs['orderBy'] }
      : { orderBy?: BestiaryEditorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BestiaryEditorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBestiaryEditorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BestiaryEditor model
 */
readonly fields: BestiaryEditorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BestiaryEditor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BestiaryEditorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  bestiary<T extends Prisma.BestiaryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestiaryDefaultArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BestiaryEditor model
 */
export interface BestiaryEditorFieldRefs {
  readonly bestiaryId: Prisma.FieldRef<"BestiaryEditor", 'String'>
  readonly userId: Prisma.FieldRef<"BestiaryEditor", 'String'>
}
    

// Custom InputTypes
/**
 * BestiaryEditor findUnique
 */
export type BestiaryEditorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter, which BestiaryEditor to fetch.
   */
  where: Prisma.BestiaryEditorWhereUniqueInput
}

/**
 * BestiaryEditor findUniqueOrThrow
 */
export type BestiaryEditorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter, which BestiaryEditor to fetch.
   */
  where: Prisma.BestiaryEditorWhereUniqueInput
}

/**
 * BestiaryEditor findFirst
 */
export type BestiaryEditorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter, which BestiaryEditor to fetch.
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestiaryEditors to fetch.
   */
  orderBy?: Prisma.BestiaryEditorOrderByWithRelationInput | Prisma.BestiaryEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestiaryEditors.
   */
  cursor?: Prisma.BestiaryEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestiaryEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestiaryEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestiaryEditors.
   */
  distinct?: Prisma.BestiaryEditorScalarFieldEnum | Prisma.BestiaryEditorScalarFieldEnum[]
}

/**
 * BestiaryEditor findFirstOrThrow
 */
export type BestiaryEditorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter, which BestiaryEditor to fetch.
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestiaryEditors to fetch.
   */
  orderBy?: Prisma.BestiaryEditorOrderByWithRelationInput | Prisma.BestiaryEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BestiaryEditors.
   */
  cursor?: Prisma.BestiaryEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestiaryEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestiaryEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestiaryEditors.
   */
  distinct?: Prisma.BestiaryEditorScalarFieldEnum | Prisma.BestiaryEditorScalarFieldEnum[]
}

/**
 * BestiaryEditor findMany
 */
export type BestiaryEditorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter, which BestiaryEditors to fetch.
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BestiaryEditors to fetch.
   */
  orderBy?: Prisma.BestiaryEditorOrderByWithRelationInput | Prisma.BestiaryEditorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BestiaryEditors.
   */
  cursor?: Prisma.BestiaryEditorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BestiaryEditors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BestiaryEditors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BestiaryEditors.
   */
  distinct?: Prisma.BestiaryEditorScalarFieldEnum | Prisma.BestiaryEditorScalarFieldEnum[]
}

/**
 * BestiaryEditor create
 */
export type BestiaryEditorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * The data needed to create a BestiaryEditor.
   */
  data: Prisma.XOR<Prisma.BestiaryEditorCreateInput, Prisma.BestiaryEditorUncheckedCreateInput>
}

/**
 * BestiaryEditor createMany
 */
export type BestiaryEditorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BestiaryEditors.
   */
  data: Prisma.BestiaryEditorCreateManyInput | Prisma.BestiaryEditorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BestiaryEditor createManyAndReturn
 */
export type BestiaryEditorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * The data used to create many BestiaryEditors.
   */
  data: Prisma.BestiaryEditorCreateManyInput | Prisma.BestiaryEditorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * BestiaryEditor update
 */
export type BestiaryEditorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * The data needed to update a BestiaryEditor.
   */
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateInput, Prisma.BestiaryEditorUncheckedUpdateInput>
  /**
   * Choose, which BestiaryEditor to update.
   */
  where: Prisma.BestiaryEditorWhereUniqueInput
}

/**
 * BestiaryEditor updateMany
 */
export type BestiaryEditorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BestiaryEditors.
   */
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateManyMutationInput, Prisma.BestiaryEditorUncheckedUpdateManyInput>
  /**
   * Filter which BestiaryEditors to update
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * Limit how many BestiaryEditors to update.
   */
  limit?: number
}

/**
 * BestiaryEditor updateManyAndReturn
 */
export type BestiaryEditorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * The data used to update BestiaryEditors.
   */
  data: Prisma.XOR<Prisma.BestiaryEditorUpdateManyMutationInput, Prisma.BestiaryEditorUncheckedUpdateManyInput>
  /**
   * Filter which BestiaryEditors to update
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * Limit how many BestiaryEditors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * BestiaryEditor upsert
 */
export type BestiaryEditorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * The filter to search for the BestiaryEditor to update in case it exists.
   */
  where: Prisma.BestiaryEditorWhereUniqueInput
  /**
   * In case the BestiaryEditor found by the `where` argument doesn't exist, create a new BestiaryEditor with this data.
   */
  create: Prisma.XOR<Prisma.BestiaryEditorCreateInput, Prisma.BestiaryEditorUncheckedCreateInput>
  /**
   * In case the BestiaryEditor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BestiaryEditorUpdateInput, Prisma.BestiaryEditorUncheckedUpdateInput>
}

/**
 * BestiaryEditor delete
 */
export type BestiaryEditorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
  /**
   * Filter which BestiaryEditor to delete.
   */
  where: Prisma.BestiaryEditorWhereUniqueInput
}

/**
 * BestiaryEditor deleteMany
 */
export type BestiaryEditorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BestiaryEditors to delete
   */
  where?: Prisma.BestiaryEditorWhereInput
  /**
   * Limit how many BestiaryEditors to delete.
   */
  limit?: number
}

/**
 * BestiaryEditor without action
 */
export type BestiaryEditorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BestiaryEditor
   */
  select?: Prisma.BestiaryEditorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BestiaryEditor
   */
  omit?: Prisma.BestiaryEditorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BestiaryEditorInclude<ExtArgs> | null
}
