
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserBestiaryBookmark` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserBestiaryBookmark
 * 
 */
export type UserBestiaryBookmarkModel = runtime.Types.Result.DefaultSelection<Prisma.$UserBestiaryBookmarkPayload>

export type AggregateUserBestiaryBookmark = {
  _count: UserBestiaryBookmarkCountAggregateOutputType | null
  _min: UserBestiaryBookmarkMinAggregateOutputType | null
  _max: UserBestiaryBookmarkMaxAggregateOutputType | null
}

export type UserBestiaryBookmarkMinAggregateOutputType = {
  userId: string | null
  bestiaryId: string | null
  createdAt: Date | null
}

export type UserBestiaryBookmarkMaxAggregateOutputType = {
  userId: string | null
  bestiaryId: string | null
  createdAt: Date | null
}

export type UserBestiaryBookmarkCountAggregateOutputType = {
  userId: number
  bestiaryId: number
  createdAt: number
  _all: number
}


export type UserBestiaryBookmarkMinAggregateInputType = {
  userId?: true
  bestiaryId?: true
  createdAt?: true
}

export type UserBestiaryBookmarkMaxAggregateInputType = {
  userId?: true
  bestiaryId?: true
  createdAt?: true
}

export type UserBestiaryBookmarkCountAggregateInputType = {
  userId?: true
  bestiaryId?: true
  createdAt?: true
  _all?: true
}

export type UserBestiaryBookmarkAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBestiaryBookmark to aggregate.
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryBookmarks to fetch.
   */
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithRelationInput | Prisma.UserBestiaryBookmarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserBestiaryBookmarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryBookmarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryBookmarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserBestiaryBookmarks
  **/
  _count?: true | UserBestiaryBookmarkCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserBestiaryBookmarkMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserBestiaryBookmarkMaxAggregateInputType
}

export type GetUserBestiaryBookmarkAggregateType<T extends UserBestiaryBookmarkAggregateArgs> = {
      [P in keyof T & keyof AggregateUserBestiaryBookmark]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserBestiaryBookmark[P]>
    : Prisma.GetScalarType<T[P], AggregateUserBestiaryBookmark[P]>
}




export type UserBestiaryBookmarkGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBestiaryBookmarkWhereInput
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithAggregationInput | Prisma.UserBestiaryBookmarkOrderByWithAggregationInput[]
  by: Prisma.UserBestiaryBookmarkScalarFieldEnum[] | Prisma.UserBestiaryBookmarkScalarFieldEnum
  having?: Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserBestiaryBookmarkCountAggregateInputType | true
  _min?: UserBestiaryBookmarkMinAggregateInputType
  _max?: UserBestiaryBookmarkMaxAggregateInputType
}

export type UserBestiaryBookmarkGroupByOutputType = {
  userId: string
  bestiaryId: string
  createdAt: Date
  _count: UserBestiaryBookmarkCountAggregateOutputType | null
  _min: UserBestiaryBookmarkMinAggregateOutputType | null
  _max: UserBestiaryBookmarkMaxAggregateOutputType | null
}

export type GetUserBestiaryBookmarkGroupByPayload<T extends UserBestiaryBookmarkGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserBestiaryBookmarkGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserBestiaryBookmarkGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserBestiaryBookmarkGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserBestiaryBookmarkGroupByOutputType[P]>
      }
    >
  >



export type UserBestiaryBookmarkWhereInput = {
  AND?: Prisma.UserBestiaryBookmarkWhereInput | Prisma.UserBestiaryBookmarkWhereInput[]
  OR?: Prisma.UserBestiaryBookmarkWhereInput[]
  NOT?: Prisma.UserBestiaryBookmarkWhereInput | Prisma.UserBestiaryBookmarkWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBestiaryBookmark"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
}

export type UserBestiaryBookmarkOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  bestiary?: Prisma.BestiaryOrderByWithRelationInput
}

export type UserBestiaryBookmarkWhereUniqueInput = Prisma.AtLeast<{
  userId_bestiaryId?: Prisma.UserBestiaryBookmarkUserIdBestiaryIdCompoundUniqueInput
  AND?: Prisma.UserBestiaryBookmarkWhereInput | Prisma.UserBestiaryBookmarkWhereInput[]
  OR?: Prisma.UserBestiaryBookmarkWhereInput[]
  NOT?: Prisma.UserBestiaryBookmarkWhereInput | Prisma.UserBestiaryBookmarkWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBestiaryBookmark"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
}, "userId_bestiaryId">

export type UserBestiaryBookmarkOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.UserBestiaryBookmarkCountOrderByAggregateInput
  _max?: Prisma.UserBestiaryBookmarkMaxOrderByAggregateInput
  _min?: Prisma.UserBestiaryBookmarkMinOrderByAggregateInput
}

export type UserBestiaryBookmarkScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput | Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput | Prisma.UserBestiaryBookmarkScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserBestiaryBookmark"> | string
  bestiaryId?: Prisma.StringWithAggregatesFilter<"UserBestiaryBookmark"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"UserBestiaryBookmark"> | Date | string
}

export type UserBestiaryBookmarkCreateInput = {
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutBookmarksInput
  bestiary: Prisma.BestiaryCreateNestedOneWithoutBookmarkedByInput
}

export type UserBestiaryBookmarkUncheckedCreateInput = {
  userId: string
  bestiaryId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutBookmarksNestedInput
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutBookmarkedByNestedInput
}

export type UserBestiaryBookmarkUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkCreateManyInput = {
  userId: string
  bestiaryId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkListRelationFilter = {
  every?: Prisma.UserBestiaryBookmarkWhereInput
  some?: Prisma.UserBestiaryBookmarkWhereInput
  none?: Prisma.UserBestiaryBookmarkWhereInput
}

export type UserBestiaryBookmarkOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserBestiaryBookmarkUserIdBestiaryIdCompoundUniqueInput = {
  userId: string
  bestiaryId: string
}

export type UserBestiaryBookmarkCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserBestiaryBookmarkMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserBestiaryBookmarkMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type UserBestiaryBookmarkCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryBookmarkCreateWithoutUserInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyUserInputEnvelope
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
}

export type UserBestiaryBookmarkUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryBookmarkCreateWithoutUserInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyUserInputEnvelope
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
}

export type UserBestiaryBookmarkUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryBookmarkCreateWithoutUserInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyUserInputEnvelope
  set?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  delete?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  update?: Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutUserInput | Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
}

export type UserBestiaryBookmarkUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryBookmarkCreateWithoutUserInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyUserInputEnvelope
  set?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  delete?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  update?: Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutUserInput | Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
}

export type UserBestiaryBookmarkCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyBestiaryInputEnvelope
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
}

export type UserBestiaryBookmarkUncheckedCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyBestiaryInputEnvelope
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
}

export type UserBestiaryBookmarkUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyBestiaryInputEnvelope
  set?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  delete?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  update?: Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
}

export type UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput[] | Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryBookmarkCreateManyBestiaryInputEnvelope
  set?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  delete?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  connect?: Prisma.UserBestiaryBookmarkWhereUniqueInput | Prisma.UserBestiaryBookmarkWhereUniqueInput[]
  update?: Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutBestiaryInput | Prisma.UserBestiaryBookmarkUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
}

export type UserBestiaryBookmarkCreateWithoutUserInput = {
  createdAt?: Date | string
  bestiary: Prisma.BestiaryCreateNestedOneWithoutBookmarkedByInput
}

export type UserBestiaryBookmarkUncheckedCreateWithoutUserInput = {
  bestiaryId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkCreateOrConnectWithoutUserInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput>
}

export type UserBestiaryBookmarkCreateManyUserInputEnvelope = {
  data: Prisma.UserBestiaryBookmarkCreateManyUserInput | Prisma.UserBestiaryBookmarkCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserBestiaryBookmarkUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutUserInput>
}

export type UserBestiaryBookmarkUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateWithoutUserInput, Prisma.UserBestiaryBookmarkUncheckedUpdateWithoutUserInput>
}

export type UserBestiaryBookmarkUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserBestiaryBookmarkScalarWhereInput
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateManyMutationInput, Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutUserInput>
}

export type UserBestiaryBookmarkScalarWhereInput = {
  AND?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
  OR?: Prisma.UserBestiaryBookmarkScalarWhereInput[]
  NOT?: Prisma.UserBestiaryBookmarkScalarWhereInput | Prisma.UserBestiaryBookmarkScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryBookmark"> | string
  createdAt?: Prisma.DateTimeFilter<"UserBestiaryBookmark"> | Date | string
}

export type UserBestiaryBookmarkCreateWithoutBestiaryInput = {
  createdAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutBookmarksInput
}

export type UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput = {
  userId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkCreateOrConnectWithoutBestiaryInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput>
}

export type UserBestiaryBookmarkCreateManyBestiaryInputEnvelope = {
  data: Prisma.UserBestiaryBookmarkCreateManyBestiaryInput | Prisma.UserBestiaryBookmarkCreateManyBestiaryInput[]
  skipDuplicates?: boolean
}

export type UserBestiaryBookmarkUpsertWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedUpdateWithoutBestiaryInput>
  create: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedCreateWithoutBestiaryInput>
}

export type UserBestiaryBookmarkUpdateWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateWithoutBestiaryInput, Prisma.UserBestiaryBookmarkUncheckedUpdateWithoutBestiaryInput>
}

export type UserBestiaryBookmarkUpdateManyWithWhereWithoutBestiaryInput = {
  where: Prisma.UserBestiaryBookmarkScalarWhereInput
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateManyMutationInput, Prisma.UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryInput>
}

export type UserBestiaryBookmarkCreateManyUserInput = {
  bestiaryId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkUpdateWithoutUserInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutBookmarkedByNestedInput
}

export type UserBestiaryBookmarkUncheckedUpdateWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkUncheckedUpdateManyWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkCreateManyBestiaryInput = {
  userId: string
  createdAt?: Date | string
}

export type UserBestiaryBookmarkUpdateWithoutBestiaryInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutBookmarksNestedInput
}

export type UserBestiaryBookmarkUncheckedUpdateWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UserBestiaryBookmarkUncheckedUpdateManyWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type UserBestiaryBookmarkSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryBookmark"]>

export type UserBestiaryBookmarkSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryBookmark"]>

export type UserBestiaryBookmarkSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryBookmark"]>

export type UserBestiaryBookmarkSelectScalar = {
  userId?: boolean
  bestiaryId?: boolean
  createdAt?: boolean
}

export type UserBestiaryBookmarkOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "bestiaryId" | "createdAt", ExtArgs["result"]["userBestiaryBookmark"]>
export type UserBestiaryBookmarkInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}
export type UserBestiaryBookmarkIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}
export type UserBestiaryBookmarkIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}

export type $UserBestiaryBookmarkPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserBestiaryBookmark"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    bestiary: Prisma.$BestiaryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    bestiaryId: string
    createdAt: Date
  }, ExtArgs["result"]["userBestiaryBookmark"]>
  composites: {}
}

export type UserBestiaryBookmarkGetPayload<S extends boolean | null | undefined | UserBestiaryBookmarkDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload, S>

export type UserBestiaryBookmarkCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserBestiaryBookmarkFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserBestiaryBookmarkCountAggregateInputType | true
  }

export interface UserBestiaryBookmarkDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserBestiaryBookmark'], meta: { name: 'UserBestiaryBookmark' } }
  /**
   * Find zero or one UserBestiaryBookmark that matches the filter.
   * @param {UserBestiaryBookmarkFindUniqueArgs} args - Arguments to find a UserBestiaryBookmark
   * @example
   * // Get one UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserBestiaryBookmarkFindUniqueArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserBestiaryBookmark that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserBestiaryBookmarkFindUniqueOrThrowArgs} args - Arguments to find a UserBestiaryBookmark
   * @example
   * // Get one UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserBestiaryBookmarkFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBestiaryBookmark that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkFindFirstArgs} args - Arguments to find a UserBestiaryBookmark
   * @example
   * // Get one UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserBestiaryBookmarkFindFirstArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBestiaryBookmark that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkFindFirstOrThrowArgs} args - Arguments to find a UserBestiaryBookmark
   * @example
   * // Get one UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserBestiaryBookmarkFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserBestiaryBookmarks that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserBestiaryBookmarks
   * const userBestiaryBookmarks = await prisma.userBestiaryBookmark.findMany()
   * 
   * // Get first 10 UserBestiaryBookmarks
   * const userBestiaryBookmarks = await prisma.userBestiaryBookmark.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userBestiaryBookmarkWithUserIdOnly = await prisma.userBestiaryBookmark.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserBestiaryBookmarkFindManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserBestiaryBookmark.
   * @param {UserBestiaryBookmarkCreateArgs} args - Arguments to create a UserBestiaryBookmark.
   * @example
   * // Create one UserBestiaryBookmark
   * const UserBestiaryBookmark = await prisma.userBestiaryBookmark.create({
   *   data: {
   *     // ... data to create a UserBestiaryBookmark
   *   }
   * })
   * 
   */
  create<T extends UserBestiaryBookmarkCreateArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkCreateArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserBestiaryBookmarks.
   * @param {UserBestiaryBookmarkCreateManyArgs} args - Arguments to create many UserBestiaryBookmarks.
   * @example
   * // Create many UserBestiaryBookmarks
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserBestiaryBookmarkCreateManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserBestiaryBookmarks and returns the data saved in the database.
   * @param {UserBestiaryBookmarkCreateManyAndReturnArgs} args - Arguments to create many UserBestiaryBookmarks.
   * @example
   * // Create many UserBestiaryBookmarks
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserBestiaryBookmarks and only return the `userId`
   * const userBestiaryBookmarkWithUserIdOnly = await prisma.userBestiaryBookmark.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserBestiaryBookmarkCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserBestiaryBookmark.
   * @param {UserBestiaryBookmarkDeleteArgs} args - Arguments to delete one UserBestiaryBookmark.
   * @example
   * // Delete one UserBestiaryBookmark
   * const UserBestiaryBookmark = await prisma.userBestiaryBookmark.delete({
   *   where: {
   *     // ... filter to delete one UserBestiaryBookmark
   *   }
   * })
   * 
   */
  delete<T extends UserBestiaryBookmarkDeleteArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkDeleteArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserBestiaryBookmark.
   * @param {UserBestiaryBookmarkUpdateArgs} args - Arguments to update one UserBestiaryBookmark.
   * @example
   * // Update one UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserBestiaryBookmarkUpdateArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkUpdateArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserBestiaryBookmarks.
   * @param {UserBestiaryBookmarkDeleteManyArgs} args - Arguments to filter UserBestiaryBookmarks to delete.
   * @example
   * // Delete a few UserBestiaryBookmarks
   * const { count } = await prisma.userBestiaryBookmark.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserBestiaryBookmarkDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryBookmarkDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBestiaryBookmarks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserBestiaryBookmarks
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserBestiaryBookmarkUpdateManyArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBestiaryBookmarks and returns the data updated in the database.
   * @param {UserBestiaryBookmarkUpdateManyAndReturnArgs} args - Arguments to update many UserBestiaryBookmarks.
   * @example
   * // Update many UserBestiaryBookmarks
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserBestiaryBookmarks and only return the `userId`
   * const userBestiaryBookmarkWithUserIdOnly = await prisma.userBestiaryBookmark.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserBestiaryBookmarkUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserBestiaryBookmark.
   * @param {UserBestiaryBookmarkUpsertArgs} args - Arguments to update or create a UserBestiaryBookmark.
   * @example
   * // Update or create a UserBestiaryBookmark
   * const userBestiaryBookmark = await prisma.userBestiaryBookmark.upsert({
   *   create: {
   *     // ... data to create a UserBestiaryBookmark
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserBestiaryBookmark we want to update
   *   }
   * })
   */
  upsert<T extends UserBestiaryBookmarkUpsertArgs>(args: Prisma.SelectSubset<T, UserBestiaryBookmarkUpsertArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryBookmarkClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryBookmarkPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserBestiaryBookmarks.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkCountArgs} args - Arguments to filter UserBestiaryBookmarks to count.
   * @example
   * // Count the number of UserBestiaryBookmarks
   * const count = await prisma.userBestiaryBookmark.count({
   *   where: {
   *     // ... the filter for the UserBestiaryBookmarks we want to count
   *   }
   * })
  **/
  count<T extends UserBestiaryBookmarkCountArgs>(
    args?: Prisma.Subset<T, UserBestiaryBookmarkCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserBestiaryBookmarkCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserBestiaryBookmark.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserBestiaryBookmarkAggregateArgs>(args: Prisma.Subset<T, UserBestiaryBookmarkAggregateArgs>): Prisma.PrismaPromise<GetUserBestiaryBookmarkAggregateType<T>>

  /**
   * Group by UserBestiaryBookmark.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryBookmarkGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserBestiaryBookmarkGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserBestiaryBookmarkGroupByArgs['orderBy'] }
      : { orderBy?: UserBestiaryBookmarkGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserBestiaryBookmarkGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserBestiaryBookmarkGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserBestiaryBookmark model
 */
readonly fields: UserBestiaryBookmarkFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserBestiaryBookmark.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserBestiaryBookmarkClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bestiary<T extends Prisma.BestiaryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestiaryDefaultArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserBestiaryBookmark model
 */
export interface UserBestiaryBookmarkFieldRefs {
  readonly userId: Prisma.FieldRef<"UserBestiaryBookmark", 'String'>
  readonly bestiaryId: Prisma.FieldRef<"UserBestiaryBookmark", 'String'>
  readonly createdAt: Prisma.FieldRef<"UserBestiaryBookmark", 'DateTime'>
}
    

// Custom InputTypes
/**
 * UserBestiaryBookmark findUnique
 */
export type UserBestiaryBookmarkFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryBookmark to fetch.
   */
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
}

/**
 * UserBestiaryBookmark findUniqueOrThrow
 */
export type UserBestiaryBookmarkFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryBookmark to fetch.
   */
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
}

/**
 * UserBestiaryBookmark findFirst
 */
export type UserBestiaryBookmarkFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryBookmark to fetch.
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryBookmarks to fetch.
   */
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithRelationInput | Prisma.UserBestiaryBookmarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBestiaryBookmarks.
   */
  cursor?: Prisma.UserBestiaryBookmarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryBookmarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryBookmarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryBookmarks.
   */
  distinct?: Prisma.UserBestiaryBookmarkScalarFieldEnum | Prisma.UserBestiaryBookmarkScalarFieldEnum[]
}

/**
 * UserBestiaryBookmark findFirstOrThrow
 */
export type UserBestiaryBookmarkFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryBookmark to fetch.
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryBookmarks to fetch.
   */
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithRelationInput | Prisma.UserBestiaryBookmarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBestiaryBookmarks.
   */
  cursor?: Prisma.UserBestiaryBookmarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryBookmarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryBookmarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryBookmarks.
   */
  distinct?: Prisma.UserBestiaryBookmarkScalarFieldEnum | Prisma.UserBestiaryBookmarkScalarFieldEnum[]
}

/**
 * UserBestiaryBookmark findMany
 */
export type UserBestiaryBookmarkFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryBookmarks to fetch.
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryBookmarks to fetch.
   */
  orderBy?: Prisma.UserBestiaryBookmarkOrderByWithRelationInput | Prisma.UserBestiaryBookmarkOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserBestiaryBookmarks.
   */
  cursor?: Prisma.UserBestiaryBookmarkWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryBookmarks from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryBookmarks.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryBookmarks.
   */
  distinct?: Prisma.UserBestiaryBookmarkScalarFieldEnum | Prisma.UserBestiaryBookmarkScalarFieldEnum[]
}

/**
 * UserBestiaryBookmark create
 */
export type UserBestiaryBookmarkCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * The data needed to create a UserBestiaryBookmark.
   */
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateInput, Prisma.UserBestiaryBookmarkUncheckedCreateInput>
}

/**
 * UserBestiaryBookmark createMany
 */
export type UserBestiaryBookmarkCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserBestiaryBookmarks.
   */
  data: Prisma.UserBestiaryBookmarkCreateManyInput | Prisma.UserBestiaryBookmarkCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBestiaryBookmark createManyAndReturn
 */
export type UserBestiaryBookmarkCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * The data used to create many UserBestiaryBookmarks.
   */
  data: Prisma.UserBestiaryBookmarkCreateManyInput | Prisma.UserBestiaryBookmarkCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserBestiaryBookmark update
 */
export type UserBestiaryBookmarkUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * The data needed to update a UserBestiaryBookmark.
   */
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateInput, Prisma.UserBestiaryBookmarkUncheckedUpdateInput>
  /**
   * Choose, which UserBestiaryBookmark to update.
   */
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
}

/**
 * UserBestiaryBookmark updateMany
 */
export type UserBestiaryBookmarkUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserBestiaryBookmarks.
   */
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateManyMutationInput, Prisma.UserBestiaryBookmarkUncheckedUpdateManyInput>
  /**
   * Filter which UserBestiaryBookmarks to update
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * Limit how many UserBestiaryBookmarks to update.
   */
  limit?: number
}

/**
 * UserBestiaryBookmark updateManyAndReturn
 */
export type UserBestiaryBookmarkUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * The data used to update UserBestiaryBookmarks.
   */
  data: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateManyMutationInput, Prisma.UserBestiaryBookmarkUncheckedUpdateManyInput>
  /**
   * Filter which UserBestiaryBookmarks to update
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * Limit how many UserBestiaryBookmarks to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserBestiaryBookmark upsert
 */
export type UserBestiaryBookmarkUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * The filter to search for the UserBestiaryBookmark to update in case it exists.
   */
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
  /**
   * In case the UserBestiaryBookmark found by the `where` argument doesn't exist, create a new UserBestiaryBookmark with this data.
   */
  create: Prisma.XOR<Prisma.UserBestiaryBookmarkCreateInput, Prisma.UserBestiaryBookmarkUncheckedCreateInput>
  /**
   * In case the UserBestiaryBookmark was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserBestiaryBookmarkUpdateInput, Prisma.UserBestiaryBookmarkUncheckedUpdateInput>
}

/**
 * UserBestiaryBookmark delete
 */
export type UserBestiaryBookmarkDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
  /**
   * Filter which UserBestiaryBookmark to delete.
   */
  where: Prisma.UserBestiaryBookmarkWhereUniqueInput
}

/**
 * UserBestiaryBookmark deleteMany
 */
export type UserBestiaryBookmarkDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBestiaryBookmarks to delete
   */
  where?: Prisma.UserBestiaryBookmarkWhereInput
  /**
   * Limit how many UserBestiaryBookmarks to delete.
   */
  limit?: number
}

/**
 * UserBestiaryBookmark without action
 */
export type UserBestiaryBookmarkDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryBookmark
   */
  select?: Prisma.UserBestiaryBookmarkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryBookmark
   */
  omit?: Prisma.UserBestiaryBookmarkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryBookmarkInclude<ExtArgs> | null
}
