
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UserBestiaryOrder` model and its related types.
 *
 * 🟢 You can import this file directly.
 */

import type * as PJTG from '../pjtg';
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UserBestiaryOrder
 * 
 */
export type UserBestiaryOrderModel = runtime.Types.Result.DefaultSelection<Prisma.$UserBestiaryOrderPayload>

export type AggregateUserBestiaryOrder = {
  _count: UserBestiaryOrderCountAggregateOutputType | null
  _avg: UserBestiaryOrderAvgAggregateOutputType | null
  _sum: UserBestiaryOrderSumAggregateOutputType | null
  _min: UserBestiaryOrderMinAggregateOutputType | null
  _max: UserBestiaryOrderMaxAggregateOutputType | null
}

export type UserBestiaryOrderAvgAggregateOutputType = {
  index: number | null
}

export type UserBestiaryOrderSumAggregateOutputType = {
  index: number | null
}

export type UserBestiaryOrderMinAggregateOutputType = {
  userId: string | null
  bestiaryId: string | null
  index: number | null
}

export type UserBestiaryOrderMaxAggregateOutputType = {
  userId: string | null
  bestiaryId: string | null
  index: number | null
}

export type UserBestiaryOrderCountAggregateOutputType = {
  userId: number
  bestiaryId: number
  index: number
  _all: number
}


export type UserBestiaryOrderAvgAggregateInputType = {
  index?: true
}

export type UserBestiaryOrderSumAggregateInputType = {
  index?: true
}

export type UserBestiaryOrderMinAggregateInputType = {
  userId?: true
  bestiaryId?: true
  index?: true
}

export type UserBestiaryOrderMaxAggregateInputType = {
  userId?: true
  bestiaryId?: true
  index?: true
}

export type UserBestiaryOrderCountAggregateInputType = {
  userId?: true
  bestiaryId?: true
  index?: true
  _all?: true
}

export type UserBestiaryOrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBestiaryOrder to aggregate.
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryOrders to fetch.
   */
  orderBy?: Prisma.UserBestiaryOrderOrderByWithRelationInput | Prisma.UserBestiaryOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UserBestiaryOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UserBestiaryOrders
  **/
  _count?: true | UserBestiaryOrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UserBestiaryOrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UserBestiaryOrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UserBestiaryOrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UserBestiaryOrderMaxAggregateInputType
}

export type GetUserBestiaryOrderAggregateType<T extends UserBestiaryOrderAggregateArgs> = {
      [P in keyof T & keyof AggregateUserBestiaryOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUserBestiaryOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateUserBestiaryOrder[P]>
}




export type UserBestiaryOrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UserBestiaryOrderWhereInput
  orderBy?: Prisma.UserBestiaryOrderOrderByWithAggregationInput | Prisma.UserBestiaryOrderOrderByWithAggregationInput[]
  by: Prisma.UserBestiaryOrderScalarFieldEnum[] | Prisma.UserBestiaryOrderScalarFieldEnum
  having?: Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UserBestiaryOrderCountAggregateInputType | true
  _avg?: UserBestiaryOrderAvgAggregateInputType
  _sum?: UserBestiaryOrderSumAggregateInputType
  _min?: UserBestiaryOrderMinAggregateInputType
  _max?: UserBestiaryOrderMaxAggregateInputType
}

export type UserBestiaryOrderGroupByOutputType = {
  userId: string
  bestiaryId: string
  index: number
  _count: UserBestiaryOrderCountAggregateOutputType | null
  _avg: UserBestiaryOrderAvgAggregateOutputType | null
  _sum: UserBestiaryOrderSumAggregateOutputType | null
  _min: UserBestiaryOrderMinAggregateOutputType | null
  _max: UserBestiaryOrderMaxAggregateOutputType | null
}

export type GetUserBestiaryOrderGroupByPayload<T extends UserBestiaryOrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UserBestiaryOrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UserBestiaryOrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UserBestiaryOrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UserBestiaryOrderGroupByOutputType[P]>
      }
    >
  >



export type UserBestiaryOrderWhereInput = {
  AND?: Prisma.UserBestiaryOrderWhereInput | Prisma.UserBestiaryOrderWhereInput[]
  OR?: Prisma.UserBestiaryOrderWhereInput[]
  NOT?: Prisma.UserBestiaryOrderWhereInput | Prisma.UserBestiaryOrderWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  index?: Prisma.IntFilter<"UserBestiaryOrder"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
}

export type UserBestiaryOrderOrderByWithRelationInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  bestiary?: Prisma.BestiaryOrderByWithRelationInput
}

export type UserBestiaryOrderWhereUniqueInput = Prisma.AtLeast<{
  userId_bestiaryId?: Prisma.UserBestiaryOrderUserIdBestiaryIdCompoundUniqueInput
  AND?: Prisma.UserBestiaryOrderWhereInput | Prisma.UserBestiaryOrderWhereInput[]
  OR?: Prisma.UserBestiaryOrderWhereInput[]
  NOT?: Prisma.UserBestiaryOrderWhereInput | Prisma.UserBestiaryOrderWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  index?: Prisma.IntFilter<"UserBestiaryOrder"> | number
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  bestiary?: Prisma.XOR<Prisma.BestiaryScalarRelationFilter, Prisma.BestiaryWhereInput>
}, "userId_bestiaryId">

export type UserBestiaryOrderOrderByWithAggregationInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  index?: Prisma.SortOrder
  _count?: Prisma.UserBestiaryOrderCountOrderByAggregateInput
  _avg?: Prisma.UserBestiaryOrderAvgOrderByAggregateInput
  _max?: Prisma.UserBestiaryOrderMaxOrderByAggregateInput
  _min?: Prisma.UserBestiaryOrderMinOrderByAggregateInput
  _sum?: Prisma.UserBestiaryOrderSumOrderByAggregateInput
}

export type UserBestiaryOrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput | Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput | Prisma.UserBestiaryOrderScalarWhereWithAggregatesInput[]
  userId?: Prisma.StringWithAggregatesFilter<"UserBestiaryOrder"> | string
  bestiaryId?: Prisma.StringWithAggregatesFilter<"UserBestiaryOrder"> | string
  index?: Prisma.IntWithAggregatesFilter<"UserBestiaryOrder"> | number
}

export type UserBestiaryOrderCreateInput = {
  index: number
  user: Prisma.UserCreateNestedOneWithoutOrderedInput
  bestiary: Prisma.BestiaryCreateNestedOneWithoutOrderedByInput
}

export type UserBestiaryOrderUncheckedCreateInput = {
  userId: string
  bestiaryId: string
  index: number
}

export type UserBestiaryOrderUpdateInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutOrderedNestedInput
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutOrderedByNestedInput
}

export type UserBestiaryOrderUncheckedUpdateInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderCreateManyInput = {
  userId: string
  bestiaryId: string
  index: number
}

export type UserBestiaryOrderUpdateManyMutationInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderUncheckedUpdateManyInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderListRelationFilter = {
  every?: Prisma.UserBestiaryOrderWhereInput
  some?: Prisma.UserBestiaryOrderWhereInput
  none?: Prisma.UserBestiaryOrderWhereInput
}

export type UserBestiaryOrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UserBestiaryOrderUserIdBestiaryIdCompoundUniqueInput = {
  userId: string
  bestiaryId: string
}

export type UserBestiaryOrderCountOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  index?: Prisma.SortOrder
}

export type UserBestiaryOrderAvgOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type UserBestiaryOrderMaxOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  index?: Prisma.SortOrder
}

export type UserBestiaryOrderMinOrderByAggregateInput = {
  userId?: Prisma.SortOrder
  bestiaryId?: Prisma.SortOrder
  index?: Prisma.SortOrder
}

export type UserBestiaryOrderSumOrderByAggregateInput = {
  index?: Prisma.SortOrder
}

export type UserBestiaryOrderCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryOrderCreateWithoutUserInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyUserInputEnvelope
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
}

export type UserBestiaryOrderUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryOrderCreateWithoutUserInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyUserInputEnvelope
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
}

export type UserBestiaryOrderUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryOrderCreateWithoutUserInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyUserInputEnvelope
  set?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  delete?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  update?: Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutUserInput | Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
}

export type UserBestiaryOrderUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput> | Prisma.UserBestiaryOrderCreateWithoutUserInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyUserInputEnvelope
  set?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  delete?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  update?: Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutUserInput | Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutUserInput | Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
}

export type UserBestiaryOrderCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryOrderCreateWithoutBestiaryInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyBestiaryInputEnvelope
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
}

export type UserBestiaryOrderUncheckedCreateNestedManyWithoutBestiaryInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryOrderCreateWithoutBestiaryInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyBestiaryInputEnvelope
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
}

export type UserBestiaryOrderUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryOrderCreateWithoutBestiaryInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyBestiaryInputEnvelope
  set?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  delete?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  update?: Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutBestiaryInput | Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
}

export type UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryNestedInput = {
  create?: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput> | Prisma.UserBestiaryOrderCreateWithoutBestiaryInput[] | Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput[]
  connectOrCreate?: Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput | Prisma.UserBestiaryOrderCreateOrConnectWithoutBestiaryInput[]
  upsert?: Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryOrderUpsertWithWhereUniqueWithoutBestiaryInput[]
  createMany?: Prisma.UserBestiaryOrderCreateManyBestiaryInputEnvelope
  set?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  disconnect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  delete?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  connect?: Prisma.UserBestiaryOrderWhereUniqueInput | Prisma.UserBestiaryOrderWhereUniqueInput[]
  update?: Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutBestiaryInput | Prisma.UserBestiaryOrderUpdateWithWhereUniqueWithoutBestiaryInput[]
  updateMany?: Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutBestiaryInput | Prisma.UserBestiaryOrderUpdateManyWithWhereWithoutBestiaryInput[]
  deleteMany?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
}

export type UserBestiaryOrderCreateWithoutUserInput = {
  index: number
  bestiary: Prisma.BestiaryCreateNestedOneWithoutOrderedByInput
}

export type UserBestiaryOrderUncheckedCreateWithoutUserInput = {
  bestiaryId: string
  index: number
}

export type UserBestiaryOrderCreateOrConnectWithoutUserInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput>
}

export type UserBestiaryOrderCreateManyUserInputEnvelope = {
  data: Prisma.UserBestiaryOrderCreateManyUserInput | Prisma.UserBestiaryOrderCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type UserBestiaryOrderUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBestiaryOrderUpdateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutUserInput>
}

export type UserBestiaryOrderUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateWithoutUserInput, Prisma.UserBestiaryOrderUncheckedUpdateWithoutUserInput>
}

export type UserBestiaryOrderUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.UserBestiaryOrderScalarWhereInput
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateManyMutationInput, Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutUserInput>
}

export type UserBestiaryOrderScalarWhereInput = {
  AND?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
  OR?: Prisma.UserBestiaryOrderScalarWhereInput[]
  NOT?: Prisma.UserBestiaryOrderScalarWhereInput | Prisma.UserBestiaryOrderScalarWhereInput[]
  userId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  bestiaryId?: Prisma.StringFilter<"UserBestiaryOrder"> | string
  index?: Prisma.IntFilter<"UserBestiaryOrder"> | number
}

export type UserBestiaryOrderCreateWithoutBestiaryInput = {
  index: number
  user: Prisma.UserCreateNestedOneWithoutOrderedInput
}

export type UserBestiaryOrderUncheckedCreateWithoutBestiaryInput = {
  userId: string
  index: number
}

export type UserBestiaryOrderCreateOrConnectWithoutBestiaryInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  create: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput>
}

export type UserBestiaryOrderCreateManyBestiaryInputEnvelope = {
  data: Prisma.UserBestiaryOrderCreateManyBestiaryInput | Prisma.UserBestiaryOrderCreateManyBestiaryInput[]
  skipDuplicates?: boolean
}

export type UserBestiaryOrderUpsertWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  update: Prisma.XOR<Prisma.UserBestiaryOrderUpdateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedUpdateWithoutBestiaryInput>
  create: Prisma.XOR<Prisma.UserBestiaryOrderCreateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedCreateWithoutBestiaryInput>
}

export type UserBestiaryOrderUpdateWithWhereUniqueWithoutBestiaryInput = {
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateWithoutBestiaryInput, Prisma.UserBestiaryOrderUncheckedUpdateWithoutBestiaryInput>
}

export type UserBestiaryOrderUpdateManyWithWhereWithoutBestiaryInput = {
  where: Prisma.UserBestiaryOrderScalarWhereInput
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateManyMutationInput, Prisma.UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryInput>
}

export type UserBestiaryOrderCreateManyUserInput = {
  bestiaryId: string
  index: number
}

export type UserBestiaryOrderUpdateWithoutUserInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  bestiary?: Prisma.BestiaryUpdateOneRequiredWithoutOrderedByNestedInput
}

export type UserBestiaryOrderUncheckedUpdateWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderUncheckedUpdateManyWithoutUserInput = {
  bestiaryId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderCreateManyBestiaryInput = {
  userId: string
  index: number
}

export type UserBestiaryOrderUpdateWithoutBestiaryInput = {
  index?: Prisma.IntFieldUpdateOperationsInput | number
  user?: Prisma.UserUpdateOneRequiredWithoutOrderedNestedInput
}

export type UserBestiaryOrderUncheckedUpdateWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UserBestiaryOrderUncheckedUpdateManyWithoutBestiaryInput = {
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
}



export type UserBestiaryOrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  index?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryOrder"]>

export type UserBestiaryOrderSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  index?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryOrder"]>

export type UserBestiaryOrderSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  userId?: boolean
  bestiaryId?: boolean
  index?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["userBestiaryOrder"]>

export type UserBestiaryOrderSelectScalar = {
  userId?: boolean
  bestiaryId?: boolean
  index?: boolean
}

export type UserBestiaryOrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"userId" | "bestiaryId" | "index", ExtArgs["result"]["userBestiaryOrder"]>
export type UserBestiaryOrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}
export type UserBestiaryOrderIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}
export type UserBestiaryOrderIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  bestiary?: boolean | Prisma.BestiaryDefaultArgs<ExtArgs>
}

export type $UserBestiaryOrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UserBestiaryOrder"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    bestiary: Prisma.$BestiaryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    userId: string
    bestiaryId: string
    index: number
  }, ExtArgs["result"]["userBestiaryOrder"]>
  composites: {}
}

export type UserBestiaryOrderGetPayload<S extends boolean | null | undefined | UserBestiaryOrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload, S>

export type UserBestiaryOrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UserBestiaryOrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UserBestiaryOrderCountAggregateInputType | true
  }

export interface UserBestiaryOrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UserBestiaryOrder'], meta: { name: 'UserBestiaryOrder' } }
  /**
   * Find zero or one UserBestiaryOrder that matches the filter.
   * @param {UserBestiaryOrderFindUniqueArgs} args - Arguments to find a UserBestiaryOrder
   * @example
   * // Get one UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UserBestiaryOrderFindUniqueArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UserBestiaryOrder that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UserBestiaryOrderFindUniqueOrThrowArgs} args - Arguments to find a UserBestiaryOrder
   * @example
   * // Get one UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UserBestiaryOrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBestiaryOrder that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderFindFirstArgs} args - Arguments to find a UserBestiaryOrder
   * @example
   * // Get one UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UserBestiaryOrderFindFirstArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UserBestiaryOrder that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderFindFirstOrThrowArgs} args - Arguments to find a UserBestiaryOrder
   * @example
   * // Get one UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UserBestiaryOrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UserBestiaryOrders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UserBestiaryOrders
   * const userBestiaryOrders = await prisma.userBestiaryOrder.findMany()
   * 
   * // Get first 10 UserBestiaryOrders
   * const userBestiaryOrders = await prisma.userBestiaryOrder.findMany({ take: 10 })
   * 
   * // Only select the `userId`
   * const userBestiaryOrderWithUserIdOnly = await prisma.userBestiaryOrder.findMany({ select: { userId: true } })
   * 
   */
  findMany<T extends UserBestiaryOrderFindManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UserBestiaryOrder.
   * @param {UserBestiaryOrderCreateArgs} args - Arguments to create a UserBestiaryOrder.
   * @example
   * // Create one UserBestiaryOrder
   * const UserBestiaryOrder = await prisma.userBestiaryOrder.create({
   *   data: {
   *     // ... data to create a UserBestiaryOrder
   *   }
   * })
   * 
   */
  create<T extends UserBestiaryOrderCreateArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderCreateArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UserBestiaryOrders.
   * @param {UserBestiaryOrderCreateManyArgs} args - Arguments to create many UserBestiaryOrders.
   * @example
   * // Create many UserBestiaryOrders
   * const userBestiaryOrder = await prisma.userBestiaryOrder.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UserBestiaryOrderCreateManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UserBestiaryOrders and returns the data saved in the database.
   * @param {UserBestiaryOrderCreateManyAndReturnArgs} args - Arguments to create many UserBestiaryOrders.
   * @example
   * // Create many UserBestiaryOrders
   * const userBestiaryOrder = await prisma.userBestiaryOrder.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UserBestiaryOrders and only return the `userId`
   * const userBestiaryOrderWithUserIdOnly = await prisma.userBestiaryOrder.createManyAndReturn({
   *   select: { userId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UserBestiaryOrderCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UserBestiaryOrder.
   * @param {UserBestiaryOrderDeleteArgs} args - Arguments to delete one UserBestiaryOrder.
   * @example
   * // Delete one UserBestiaryOrder
   * const UserBestiaryOrder = await prisma.userBestiaryOrder.delete({
   *   where: {
   *     // ... filter to delete one UserBestiaryOrder
   *   }
   * })
   * 
   */
  delete<T extends UserBestiaryOrderDeleteArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderDeleteArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UserBestiaryOrder.
   * @param {UserBestiaryOrderUpdateArgs} args - Arguments to update one UserBestiaryOrder.
   * @example
   * // Update one UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UserBestiaryOrderUpdateArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderUpdateArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UserBestiaryOrders.
   * @param {UserBestiaryOrderDeleteManyArgs} args - Arguments to filter UserBestiaryOrders to delete.
   * @example
   * // Delete a few UserBestiaryOrders
   * const { count } = await prisma.userBestiaryOrder.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UserBestiaryOrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, UserBestiaryOrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBestiaryOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UserBestiaryOrders
   * const userBestiaryOrder = await prisma.userBestiaryOrder.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UserBestiaryOrderUpdateManyArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UserBestiaryOrders and returns the data updated in the database.
   * @param {UserBestiaryOrderUpdateManyAndReturnArgs} args - Arguments to update many UserBestiaryOrders.
   * @example
   * // Update many UserBestiaryOrders
   * const userBestiaryOrder = await prisma.userBestiaryOrder.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UserBestiaryOrders and only return the `userId`
   * const userBestiaryOrderWithUserIdOnly = await prisma.userBestiaryOrder.updateManyAndReturn({
   *   select: { userId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UserBestiaryOrderUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UserBestiaryOrder.
   * @param {UserBestiaryOrderUpsertArgs} args - Arguments to update or create a UserBestiaryOrder.
   * @example
   * // Update or create a UserBestiaryOrder
   * const userBestiaryOrder = await prisma.userBestiaryOrder.upsert({
   *   create: {
   *     // ... data to create a UserBestiaryOrder
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UserBestiaryOrder we want to update
   *   }
   * })
   */
  upsert<T extends UserBestiaryOrderUpsertArgs>(args: Prisma.SelectSubset<T, UserBestiaryOrderUpsertArgs<ExtArgs>>): Prisma.Prisma__UserBestiaryOrderClient<runtime.Types.Result.GetResult<Prisma.$UserBestiaryOrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UserBestiaryOrders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderCountArgs} args - Arguments to filter UserBestiaryOrders to count.
   * @example
   * // Count the number of UserBestiaryOrders
   * const count = await prisma.userBestiaryOrder.count({
   *   where: {
   *     // ... the filter for the UserBestiaryOrders we want to count
   *   }
   * })
  **/
  count<T extends UserBestiaryOrderCountArgs>(
    args?: Prisma.Subset<T, UserBestiaryOrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UserBestiaryOrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UserBestiaryOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UserBestiaryOrderAggregateArgs>(args: Prisma.Subset<T, UserBestiaryOrderAggregateArgs>): Prisma.PrismaPromise<GetUserBestiaryOrderAggregateType<T>>

  /**
   * Group by UserBestiaryOrder.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UserBestiaryOrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UserBestiaryOrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UserBestiaryOrderGroupByArgs['orderBy'] }
      : { orderBy?: UserBestiaryOrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UserBestiaryOrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUserBestiaryOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UserBestiaryOrder model
 */
readonly fields: UserBestiaryOrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UserBestiaryOrder.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UserBestiaryOrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  bestiary<T extends Prisma.BestiaryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BestiaryDefaultArgs<ExtArgs>>): Prisma.Prisma__BestiaryClient<runtime.Types.Result.GetResult<Prisma.$BestiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UserBestiaryOrder model
 */
export interface UserBestiaryOrderFieldRefs {
  readonly userId: Prisma.FieldRef<"UserBestiaryOrder", 'String'>
  readonly bestiaryId: Prisma.FieldRef<"UserBestiaryOrder", 'String'>
  readonly index: Prisma.FieldRef<"UserBestiaryOrder", 'Int'>
}
    

// Custom InputTypes
/**
 * UserBestiaryOrder findUnique
 */
export type UserBestiaryOrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryOrder to fetch.
   */
  where: Prisma.UserBestiaryOrderWhereUniqueInput
}

/**
 * UserBestiaryOrder findUniqueOrThrow
 */
export type UserBestiaryOrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryOrder to fetch.
   */
  where: Prisma.UserBestiaryOrderWhereUniqueInput
}

/**
 * UserBestiaryOrder findFirst
 */
export type UserBestiaryOrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryOrder to fetch.
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryOrders to fetch.
   */
  orderBy?: Prisma.UserBestiaryOrderOrderByWithRelationInput | Prisma.UserBestiaryOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBestiaryOrders.
   */
  cursor?: Prisma.UserBestiaryOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryOrders.
   */
  distinct?: Prisma.UserBestiaryOrderScalarFieldEnum | Prisma.UserBestiaryOrderScalarFieldEnum[]
}

/**
 * UserBestiaryOrder findFirstOrThrow
 */
export type UserBestiaryOrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryOrder to fetch.
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryOrders to fetch.
   */
  orderBy?: Prisma.UserBestiaryOrderOrderByWithRelationInput | Prisma.UserBestiaryOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UserBestiaryOrders.
   */
  cursor?: Prisma.UserBestiaryOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryOrders.
   */
  distinct?: Prisma.UserBestiaryOrderScalarFieldEnum | Prisma.UserBestiaryOrderScalarFieldEnum[]
}

/**
 * UserBestiaryOrder findMany
 */
export type UserBestiaryOrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter, which UserBestiaryOrders to fetch.
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UserBestiaryOrders to fetch.
   */
  orderBy?: Prisma.UserBestiaryOrderOrderByWithRelationInput | Prisma.UserBestiaryOrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UserBestiaryOrders.
   */
  cursor?: Prisma.UserBestiaryOrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UserBestiaryOrders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UserBestiaryOrders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UserBestiaryOrders.
   */
  distinct?: Prisma.UserBestiaryOrderScalarFieldEnum | Prisma.UserBestiaryOrderScalarFieldEnum[]
}

/**
 * UserBestiaryOrder create
 */
export type UserBestiaryOrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * The data needed to create a UserBestiaryOrder.
   */
  data: Prisma.XOR<Prisma.UserBestiaryOrderCreateInput, Prisma.UserBestiaryOrderUncheckedCreateInput>
}

/**
 * UserBestiaryOrder createMany
 */
export type UserBestiaryOrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UserBestiaryOrders.
   */
  data: Prisma.UserBestiaryOrderCreateManyInput | Prisma.UserBestiaryOrderCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UserBestiaryOrder createManyAndReturn
 */
export type UserBestiaryOrderCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * The data used to create many UserBestiaryOrders.
   */
  data: Prisma.UserBestiaryOrderCreateManyInput | Prisma.UserBestiaryOrderCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UserBestiaryOrder update
 */
export type UserBestiaryOrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * The data needed to update a UserBestiaryOrder.
   */
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateInput, Prisma.UserBestiaryOrderUncheckedUpdateInput>
  /**
   * Choose, which UserBestiaryOrder to update.
   */
  where: Prisma.UserBestiaryOrderWhereUniqueInput
}

/**
 * UserBestiaryOrder updateMany
 */
export type UserBestiaryOrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UserBestiaryOrders.
   */
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateManyMutationInput, Prisma.UserBestiaryOrderUncheckedUpdateManyInput>
  /**
   * Filter which UserBestiaryOrders to update
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * Limit how many UserBestiaryOrders to update.
   */
  limit?: number
}

/**
 * UserBestiaryOrder updateManyAndReturn
 */
export type UserBestiaryOrderUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * The data used to update UserBestiaryOrders.
   */
  data: Prisma.XOR<Prisma.UserBestiaryOrderUpdateManyMutationInput, Prisma.UserBestiaryOrderUncheckedUpdateManyInput>
  /**
   * Filter which UserBestiaryOrders to update
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * Limit how many UserBestiaryOrders to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UserBestiaryOrder upsert
 */
export type UserBestiaryOrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * The filter to search for the UserBestiaryOrder to update in case it exists.
   */
  where: Prisma.UserBestiaryOrderWhereUniqueInput
  /**
   * In case the UserBestiaryOrder found by the `where` argument doesn't exist, create a new UserBestiaryOrder with this data.
   */
  create: Prisma.XOR<Prisma.UserBestiaryOrderCreateInput, Prisma.UserBestiaryOrderUncheckedCreateInput>
  /**
   * In case the UserBestiaryOrder was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UserBestiaryOrderUpdateInput, Prisma.UserBestiaryOrderUncheckedUpdateInput>
}

/**
 * UserBestiaryOrder delete
 */
export type UserBestiaryOrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
  /**
   * Filter which UserBestiaryOrder to delete.
   */
  where: Prisma.UserBestiaryOrderWhereUniqueInput
}

/**
 * UserBestiaryOrder deleteMany
 */
export type UserBestiaryOrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UserBestiaryOrders to delete
   */
  where?: Prisma.UserBestiaryOrderWhereInput
  /**
   * Limit how many UserBestiaryOrders to delete.
   */
  limit?: number
}

/**
 * UserBestiaryOrder without action
 */
export type UserBestiaryOrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UserBestiaryOrder
   */
  select?: Prisma.UserBestiaryOrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UserBestiaryOrder
   */
  omit?: Prisma.UserBestiaryOrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserBestiaryOrderInclude<ExtArgs> | null
}
