name: Build site for production
on:
    push:
        branches:
            - main
env:
    NODE_ENV: production
jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: oven-sh/setup-bun@v1
            - name: Installing shared project dependencies
              working-directory: ./shared
              run: bun install
            - name: Installing frontend dependencies
              working-directory: ./frontend
              run: bun install
            - name: Installing backend dependencies
              working-directory: ./backend
              run: bun install
            - name: Building the frontend
              working-directory: ./frontend
              run: bun run build
            - name: Building the backend
              working-directory: ./backend
              run: bun run compile
            - name: Deploy to branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: output
                  FOLDER: ./build
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
