name: Build site for production
on:
    release:
        types: [published]
    workflow_dispatch:
env:
    NODE_ENV: production
jobs:
    build-and-push:
        runs-on: ubuntu-24.04-arm

        permissions:
            contents: read
            packages: write

        environment:
            name: Production
            url: https://bestiarybuilder.com

        env:
            REGISTRY: ghcr.io

        steps:
            - uses: actions/checkout@master
            - name: set lower case owner name
              run: echo "REPOSITORY=${REPOSITORY,,}" >>${GITHUB_ENV}
              env:
                  REPOSITORY: '${{ github.repository }}'
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{env.REGISTRY}}/${{env.REPOSITORY}}:latest
                  platforms: linux/arm64
                  build-args: |
                    "VITE_DISCORD_ID=${{ secrets.VITE_DISCORD_ID }}"
                    "VITE_ERROR_WEBHOOK=${{ secrets.VITE_ERROR_WEBHOOK }}"
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
