name: Check status of branch
on:
    pull_request:
env:
    NODE_ENV: production
    frontendPath: ../build/frontend
jobs:
    eslint:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
            - uses: actions/checkout@v3
            - uses: oven-sh/setup-bun@v1
            - name: Installing shared dependencies
              working-directory: ./shared
              run: bun install
            - name: Run shared ESLint
              working-directory: ./shared
              run: bun run lint
            - name: Installing frontend dependencies
              working-directory: ./frontend
              run: bun install
            - name: Run frontend ESLint
              working-directory: ./frontend
              run: bun run lint
            - name: Installing backend dependencies
              working-directory: ./backend
              run: bun install
            - name: Run backend ESLint
              working-directory: ./backend
              run: bun run lint
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: oven-sh/setup-bun@v1
            - name: Installing shared project dependencies
              working-directory: ./shared
              run: bun install
            - name: Installing frontend dependencies
              working-directory: ./frontend
              run: bun install
            - name: Building the frontend
              working-directory: ./frontend
              run: bun run build
            - name: Installing backend dependencies
              working-directory: ./backend
              run: bun install
            - name: Building the backend
              working-directory: ./backend
              run: bun run compile
            - name: Running backend tests
              working-directory: ./backend
              run: bun run test
